alphagov/verify-proxy-node

- docker-compose.yaml
- pki/Gemfile
- pki/Gemfile.lock
- pki/metadata.rb
- pki/utils.rb
- Allow specifying path to `xmlsectool` in environment variable
- Use absolute paths in `xmlsectool` command
- Get `verify-metadata-generator` gem via `https://` instead of `git@`
- Make `docker-compose.yml` version less specific for compatibility
- Use alpine ruby image to serve metadata
> BAU: Fixes for PKI generation script

- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/ResponseAssertionFactory.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/SamlSignatureValidatorFactory.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/metadata/MetadataFactory.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/TranslatorApplication.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/StubConnectorApplication.java
- Remove request references from the Translator service
- Move common classes to factories 
- Remove unused methods
> Make methods common so they can be used between classes

- .gitignore
- build.gradle
- docker-compose.yaml
- gradle-compose.yaml
- gradlew
- gradlew.bat
- pki/generate
- pki/options.rb
- proxy-node-translator/build.gradle
- proxy-node-translator/src/test/java/uk/gov/ida/notification/softhsm/SoftHSMIntegrationTest.java
- softHSM.baseImage.Dockerfile
- startup.sh
- translator.softHSM.Dockerfile
Install softHSM in the Translator container so that the proxy node signing key can be stored in and retrieved from softHSM in test environments.
Modify startup and pki generation scripts to generate the signing key files in a format that can be loaded into softHSM.
Load the signing private key into softHSM in the Dockerfile after installing softHSM so that it is available for use during testing.
Include swedenconnect/opensaml-pkcs11 in the Translator build script so that the library can be used to access keys in softHSM.  Integration tests provided to prove that softHSM and swedenconnect/opensaml-pkcs11 are installed and usable in the container (built from translator.softHSM.Dockerfile).
The docker-compose files have been modified to use the new translator.softHSM.Dockerfile, and include …
> EID-1155: Dockerize softHSM in Proxy Node Translator

- proxy-node-gateway/src/dist/config.yml
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayConfiguration.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/TranslatorService.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/TranslatorServiceConfiguration.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/HubResponseResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/TranslatorServiceTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/EidasAuthnRequestAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HubResponseAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/MetadataAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/base/GatewayAppRuleTestBase.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/GatewayAppRule.java
- proxy-node-gateway/src/test/resources/config.yml
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/hubresponse/TranslatorResponseException.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/TranslatorApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/TranslatorConfiguration.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/rules/TranslatorAppRule.java
- proxy-node-translator/src/test/resources/config.yml
The gateway often times out trying to communicate with the translator
due to the really short (500ms) connection timeout setting on the
default `HttpClient`. I've added a `TranslatorServiceConfiguration`
config class that takes the `url` and a `JerseyClientConfiguration` for
the client used to talk to the translator, allowing us to increase the
timeout.
I also pulled the bit that handles communication with the translator out
into its own class `TranslatorService` which is unit-tested in
`TranslatorServiceTest`.
The prod and test configs had drifted out of sync, so I had to update the
`Application`s and `AppRule`s to account for the `redisServerUrl` parameter.
> EID-1136: Create TranslatorService

- .gitignore
- proxy-node-acceptance-tests/Dockerfile
- proxy-node-acceptance-tests/docker-compose.yml
- proxy-node-acceptance-tests/features/support/env.rb
- proxy-node-acceptance-tests/run-tests-with-docker.sh
- proxy-node-acceptance-tests/wait-for-it.sh
Refactored the acceptance tests so that will work with the new Kubernetes cluster.
The acceptance test container waits for Selenium hub to be up before starting its tests now (it users the ['wait-for-it.sh'](https://github.com/vishnubob/wait-for-it) script todo that.
I've also enabled it so we can run the tests under Chrome instead of Firefox if needed.
> BAU: Refactored acceptance tests to work again with the k8.

- pki/Gemfile.lock
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/deprecate/AssertionSubjectConfirmationValidator.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/deprecate/BasicAssertionSubjectConfirmationValidator.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/deprecate/IdentityProviderAssertionValidator.java
- Update bundle in pki
- Remove validation to check the expected recipient id of the subject. The recipient
of the subject is set for the hub by the idp and doesn't change in the hub so when it
reaches the proxy node, the recipient id of the subject is still the hub. Therefore
this validation will fail when connected to the Hub.
- This is the same behaviour as the MSA.
> EID-1255 - Remove validation to check expected recipient id

- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/MetadataResource.java
- This will mean that whilst we use the stub in staging, we don't need to
respin it each day.
> bau - Set expiry of connector metadata to a year

- pki/generate
- proxy-node-chart/charts/proxy-node-gateway/templates/gateway-deployment.yaml
- proxy-node-chart/charts/proxy-node-translator/templates/translator-deployment.yaml
- proxy-node-chart/charts/stub-connector/templates/stub-idp-deployment.yaml
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HubResponseAppRuleTests.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/deprecate/IdpResponseValidator.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/deprecate/IdpResponseValidatorTest.java
- proxy-node-test/src/main/java/uk/gov/ida/notification/helpers/BasicCredentialBuilder.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseFromGatewayAppRuleTests.java
Proxy Node must validate the Hub SAML response using the Hub signing cert published in Hub metadata.
Presently, the current stubbed connector and IDP journey kicked off by ./startup.sh signs the response to Proxy Node with a stub **IDP** signing cert. There is no Hub in this federation.
When the Proxy Node verifies the signature of the SAML response from Hub,
it looks up the Hub signing cert in metadata published by the Hub. This lookup filters the entries by entity id and *role* QName.
In the BAU Verify Hub this cert is found using the **SPSSODescriptor** QName role. However in the stubbed federation, which has no Hub, and stubbed Hub metadata, the role for this cert is published as IDPSSODescriptor.
This PR updates the filter used for finding the Hub signing cert in Hub metadata, to use …
> EID-1257 proxy node to validate hub response with hub signing cert

- docker-compose.yml
- proxy-node-chart/charts/proxy-node-translator/templates/translator-deployment.yaml
- proxy-node-translator/Dockerfile
- proxy-node-translator/README.md
At the current state, both softHSM and Translator must be running on a
pod together where SoftHSM would share some libs across the
containers... This is weird and undesired. We can capture the required
lib and provide it to the translator container directly, making the
deployment chart smaller.
- Code review
- Run locally - see journey through
> Get required libs from SoftHSM for Translator

- build.gradle
- proxy-node-gateway/build.gradle
- proxy-node-shared/build.gradle
- proxy-node-test/build.gradle
- proxy-node-translator/build.gradle
- stub-connector/build.gradle
We're going to be changing the dependencies required by our services, so
I'm separating them by domain (eIDAS, Verify, OpenSAML) to make them easier to remove.
In future we might want to just have per-component dependency
configurations.
> BAU: Split Gradle dependency configs

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
Base64-decodes and parses the AuthnRequest before extracting the ID and
Issuer. No validation of the message is being performed at this stage,
that will be implemented in EID-1304/1305.
> EID-1308: Extract ID and Issuer from AuthnRequest

- generate-secrets.sh
- pki/configmap.yaml
- pki/generate
- pki/options.rb
- pki/secret.yaml
- proxy-node-chart/charts/proxy-node-gateway/templates/gateway-deployment.yaml
- proxy-node-chart/charts/proxy-node-translator/templates/translator-deployment.yaml
- proxy-node-chart/charts/softhsm/templates/softhsm-deployment.yaml
- proxy-node-chart/charts/stub-connector/templates/stub-connector-deployment.yaml
- proxy-node-chart/charts/stub-connector/templates/stub-idp-deployment.yaml
- proxy-node-chart/charts/stub-connector/templates/stub-metadata-deployment.yaml
- startup.sh
It's essentially the same thing, however these are in fact secrets. In
the future, we'd be looking into sealing the secrets for the K8s cluster
as they will contain Trust Stores provided from the Hub.
Now that we're generating K8s secrets, we need to be referencing a
correct thing to be mounted.
I've created a separate script for secret generation...
It's essentially the same piece of technology that is used in the
startup script, however torn down version that will do that only.
We have to Base64 all the secrets. Some double Base64....
The startup script is generating the secrets for the local deployment. I
don't want it to break the thing, but I also don't think I want to
refactor it bearing in mind that the script is already a pain.
For now, it's duplicated...
- Run `./startup.sh`
- …
> Use `Secrets` not `ConfigMaps`

- eidas-saml-parser/src/dist/config.yml
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlConfiguration.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/saml/validation/EidasAuthnRequestValidator.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/saml/validation/components/AssertionConsumerServiceValidator.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/saml/validation/components/ComparisonValidator.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/saml/validation/components/RequestIssuerValidator.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/saml/validation/components/RequestedAttributesValidator.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/saml/validation/components/SpTypeValidator.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasAuthnRequestValidatorTest.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/signing/SoftHSMKeyRetrieverService.java
- The ESP will be now be responsible for validating the eIDAS authn request
from the connector code. Set up the ESP with the classes and config needed
to carry out this validation but don't tie it into the resource yet. Will do that in a separate PR. 
- Add tests for the ESP validation
- Put in the bones in the Application class. 
- Place variables in config.yml as a placeholder, these aren't currently being set anywhere. The DefaultNotUsed will be removed once they are. 
- Add connector metadata configuration in the ESP, so the connector metadata bundle can be created to validate the Authn Request 
- Add Redis configuration so that it can validate the Message Replay on the Request
> EID-1304 - Set up the ESP the eidas authn request validator

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/base/EidasSamlParserAppRuleTestBase.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/rules/EidasSamlParserAppRule.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/saml/EidasAuthnRequestValidatorTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/SamlSignatureValidatorFactory.java
- Stop using app rule test for now
- Add unit test to test the resource of the ESP in isolation
- Validate the signature of the eidas authn request, using the connector metadata
- Rename variable variable in the SamlSignatureValidatorFactory to make them more generic
> EID-1305 - Validate signature of eidas authn request

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/ResponseDto.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
- Pull public encryption cert out of the connector metadata and store in the DTO. Will swap to the shared DTO with the Gateway once I have the destination.
> EID-1312 - Extract encryption cert out of connector metadata

- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/EidasAuthnRequestResourceTest.java
Store the `RelayState` sent by the country in the gateway http session.
We can then send this `RelayState` within the eiDAS SAML Response.
> Store eIDAS RelayState in session

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/MetadataAppRuleTests.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/MetadataAppRuleTests.java
- The ESP will be the only component using the connector metadata, so
it makes sense for it to be running the healthcheck.
- Remove Connector Metadata healtcheck from Gateway
- Add Connector Metadata healthcheck test to ESP
> EID-1333 - Add Connector Metadata healthcheck to ESP

- proxy-node-gateway/src/dist/config.yml
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayConfiguration.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/configuration/TranslatorServiceConfiguration.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HealthCheckAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/base/GatewayAppRuleTestBase.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/GatewayAppRule.java
Now that the gateway has been stripped back in its functionality there's
a lot of cruft left over in the Application class as well as the config.
It also fixes up the AppRule tests by removing the config overrides for
fields that no longer exist.
> EID-1334 Clean up gateway Application and Config

- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/verifyserviceprovider/TranslatedHubResponse.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/verifyserviceprovider/VspLevelOfAssurance.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/verifyserviceprovider/VspScenario.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/mappers/ApplicationExceptionMapper.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/mappers/AuthnRequestExceptionMapper.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/mappers/BaseExceptionMapper.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/mappers/HubResponseExceptionMapper.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/mappers/HubResponseTranslationExceptionMapper.java
- proxy-node-translator/src/dist/config.yml
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/configuration/TranslatorConfiguration.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseContainer.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/base/TranslatorAppRuleTestBase.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/rules/VspClientRule.java
Construct a valid SAML response that contains all the required attributes.
- Add `HubResponseTranslationExceptionMapper`
- Refactor exception mappers in pn-shared to extend the same base mapper
- Supply correct values to the hub response translator
> EID-1322: Return an eIDAS SAML response with correct values

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/metadata/ConnectorMetadataException.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/metadata/Metadata.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/metadata/MetadataTest.java
- proxy-node-test/src/main/resources/local-connector-metadata.xml
Retrieve the destination url (AssertionConsumerService Location) from the connector metadata in the EidasSamlApplication.  Return as part of the response to the Gateway.
Updated the EidasSaml service to use the shared EidasSamlParserResponse class.
> EID 1312: Return destination url from Connector Metadata.

- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/EidasAuthnRequestAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/base/GatewayAppRuleTestBase.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/EidasSamlParserClientRule.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestEidasSamlResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestVerifyServiceProviderResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/VerifyServiceProviderClientRule.java
This PR reinstates the gateway integration tests, and includes:
* one happy path test that processes a connector eIDAS AuthnRequest, and creates a Verify SAML payload
* integration with eidas-saml-parser and verify-service-provider
Further PRs will increase integration test coverage.
> EID-1327 Gateway integration tests

- build.gradle
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/proxy/TranslatorProxy.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/HubResponseResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/EidasAuthnRequestAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HubResponseAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/base/GatewayAppRuleTestBase.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestEidasSamlResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestTranslatorResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestVerifyServiceProviderResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/TranslatorProxyTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/Urls.java
- proxy-node-test/src/main/java/uk/gov/ida/notification/helpers/HtmlHelpers.java
Some of the shared URLS were incomplete and hard to work with.
When returning html to users we can use xpath to assert we're returning
them the correct thing.
Previously the tests were dealing with parsing saml, which we don't need
to do - gateway doesn't need to know anything about saml. Instead, we
can test the expected content of the response via xpath.
This also pushes the method for building an authn response up to the
base apprule class as it will be useful for the hub response apprule
tests.
The test resources for the VSP and the Translator were both creating
saml objects to be serialized and sent as responses. This is unnecessary
for the gateway as it is unaware of saml. We can instead just provide
strings and make sure they are passed correctly by the gateway.
This tests the …
> Eid 1337 - Apprule tests for gateway hub response endpoint

- cloudhsm/Dockerfile
- cloudhsm/init.sh
- mdgen/.dockerignore
- mdgen/.gitignore
- mdgen/Dockerfile
- mdgen/build.gradle
- mdgen/pre-commit.sh
- mdgen/src/main/java/uk/gov/ida/mdgen/MetadataGenerator.java
This adds a Docker image from the CloudHSM client and modifies the metadata generator Java code and Docker image to use the CloudHSM.
> EID-1342/1343: Sign generated metadata with CloudHSM

- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/configuration/TranslatorServiceConfiguration.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/SessionAttributeException.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/TranslatorResponseException.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/SessionAttributeExceptionMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/TranslatorResponseExceptionMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/proxy/TranslatorProxy.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/HubResponseResource.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/session/GatewaySessionData.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/session/GatewaySessionDataValidator.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/session/SessionKeys.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/EidasAuthnRequestAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HealthCheckAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HubResponseAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestTranslatorClientErrorResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestTranslatorServerErrorResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TranslatorClientRule.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/EidasSamlParserProxyTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/TranslatorProxyTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/EidasAuthnRequestResourceTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/HubResponseResourceTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/session/TestGatewaySessionDataValidator.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/hubresponse/TranslatorResponseException.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/Urls.java
It's possible that a user won't have a session when posting a hub
response to the gateway. This could be because they've deleted their
cookies, the app has been deployed and all sessions have been
invalidated or their session has timed out.
We should handle that case.
We were storing all the values we needed in the session as separate
attribute which led to a lot of duplication, especially when trying to
extract them. This moves them to an object.
Adds a custom exception and handler to handle 400 or 500 responses from
the translator. The status code is passed back to the user, and they're
shown an error page (a stand in for the moment).
> Eid 1338 - Error handling in gateway's hub response resource

- mdgen/src/main/resources/connector_template.xml.mustache
- mdgen/src/main/resources/proxy_template.xml.mustache
We need to use and accept the algorithms specified in the eIDAS
Cryptographic Requirements document:
https://joinup.ec.europa.eu/sites/default/files/document/2015-11/eidas_-_crypto_requirements_for_the_eidas_interoperability_framework_v1.0.pdf
> BAU: Fix published signing algorithms in metadata

- build.gradle
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/resources/HubResponseTranslatorResource.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/StubConnectorApplication.java
- Once the translator has receivied the response from the VSP,
we should log the hashed attributes as well request id and destination.
- Upgrade saml-libs to latest
- Upgrade to dropwizard 1.3.9
> EID-1293 - Log hashed details for eidas response

- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/base/EidasSamlParserAppRuleTestBase.java
Initial fix to make the first integration test work.
- Use SamlObjectMarshaller instead of ObjectUtils to convert the AuthnRequest to a string.  Fixes marshalling/encoding issues with the Signature and Digest.
- Use java.util.Base64 library to encode and decode on both sides of the wire for safety, rather than different libraries on each side.
> EID-1350: Fix ESP Integration Tests

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/mappers/InvalidAuthnRequestExceptionMapper.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/exceptions/mappers/SamlTransformationErrorExceptionMapper.java
- Restore and update tests checking all validation scenarios for the AuthnRequest and Signature.
- Add ExceptionMappers to the ESP component to handle exceptions thrown when these validations fail.
- Use assertJ assertions.
> EID-1350: ESP Integration Test Enhancements

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/logging/EidasAuthnRequestAttributesLogger.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/logging/CombinedAuthnRequestAttributesLogger.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/EidasAuthnRequestResourceTest.java
Cyber needs us to log the attributes of the authn request after it's
been validated by the ESP.
They need the attributes to be key/value pairs in a json log event. We're
using the logstash-console appender which is jsonifying the logs for us.
We can add custom key/value pairs to those logs by adding them to
[logbacks MDC](https://logback.qos.ch/manual/mdc.html).
There will be a follow up piece of work to this to log the hub authn request
in the VSP.
This refactors the gateway authn logging to log all the attributes in
one log message. Each attribute will appear as a key/value pair in the
json log event.
> EID-1307 Log authn request attributes in ESP

- mdgen/src/main/java/uk/gov/ida/mdgen/MetadataGenerator.java
the mdgen tool was generating metadata that instantly expired, this
updates it to 1y.
long term we should consider accepting the expiry as an arg
> fix mdgen(erated) metadata expiring instantly

- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/metadata/Metadata.java
- The logging message was a bit vague when the ESP was unable to extract the encryption certificate from the Connector Metadata. This class is only being used to for the Connector Metadata so specify that in the log message and output the EntityID of the Connector Metadata.
> bau - Improve logging when extracting encryption cert from metadata

- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/verifyserviceprovider/Attributes.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/contracts/verifyserviceprovider/TranslatedHubResponseBuilder.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/resources/HubResponseTranslatorResource.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/saml/HubResponseTranslatorTest.java
VSP now returns a list of firstnames and dates of birth.
This PR allows the translator to support this API change, and is intended to unblock integration testing efforts.
Another PR will provide the complete solution.
> VSP now returns a list of firstnames and birthDates assertions

- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/verifyserviceprovider/Attribute.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/verifyserviceprovider/Attributes.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/resources/HubResponseTranslatorResource.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
* ignore unknown properties when reading an attribute in the VSP response
* and rename `dateOfBirths` to `datesOfBirth`
> Ignore unknown properties when reading an attribute in the VSP response

- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/saml/HubResponseTranslatorTest.java
Read the string value of the firstname attribute. Reinstates two `@Ignored` tests.
A future PR is to tidy up the way we combine first and surnames into the eidas response
> Read attribute value when supplying VSP first name for eIDAS response

- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/logging/HubResponseTranslatorLoggerHelper.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/resources/HubResponseTranslatorResource.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
- Log select attributes from the eIDAS response after translation and response generation to MDC.
- AppRule tests to verify logging and logging output to console in json format.
> EID-1358: Log eIDAS Response Attributes

- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/EidasResponseBuilder.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/EidasResponseBuilderTest.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/saml/HubResponseTranslatorTest.java
- stub-connector/src/test/java/uk/gov/ida/notification/apprule/EidasResponseValidatorAppRuleTests.java
Allow HubResponseTranslator to use a builder pattern to create an eIDAS response, in preference to calling a static method on EidasResponseBuilder with many arguments.
The PR:
* refactors `EidasResponseBuilder` to create a trasnslator `Response` using Builder pattern
* updates `HubResponseTranslator` to use the builder to create a response, the assignment of values to the builder is easier to read
* Adds unit tests for `EidasResponseBuilder`
> Refactor EidasResponseBuilder to use builder pattern to create and eiDAS SAML response

- build.gradle
- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/verifyserviceprovider/Attributes.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/contracts/verifyserviceprovider/AttributesBuilder.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/contracts/verifyserviceprovider/TranslatedHubResponseBuilder.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/logging/EidasResponseAttributesHashLoggerHelper.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/logging/HubResponseTranslatorLoggerHelper.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/resources/HubResponseTranslatorResource.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/logging/EidasResponseAttributesHashLoggerParameterizedTest.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/logging/EidasResponseAttributesHashLoggerTest.java
- proxy-node-translator/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- stub-connector/src/test/java/uk/gov/ida/notification/apprule/EidasResponseValidatorAppRuleTests.java
- Create a string for hashing based on the required Response Attributes.
- Log the hash after creation.
- Unit tests to prove that the pre-hash string is correct based on the agreed rules.
- Hash must be identical to the one created in Hub on the same attributes using the same rules.
- Unit tests to identify and alert when the implementation of the rules has changed (in case this no longer matches the hub implementation).
- Removal of redundant references to Hamcrest libraries.
- Tweaks to AttributesBuilder to support many middleNames, lastNames and datesOfBirth to match-up with the payload returned from the VSP.
> EID-1363: Log Hash of Eidas Response Attributes in Proxy Node

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/logging/EidasAuthnRequestAttributesLogger.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/logging/TranslatorSigningLoggerHelper.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/SamlObjectSigner.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/SamlObjectSignerTest.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/configuration/CloudHsmSignerConfiguration.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/configuration/KeyFileSignerConfiguration.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/EidasResponseGenerator.java
- stub-connector/src/test/java/uk/gov/ida/notification/apprule/EidasResponseValidatorAppRuleTests.java
- Log when each response is signed and specify whether it is being
signed with the CloudHSM or the KeyFile
- Use MDC.remove() rather than MDC.clear() to preserve state of MDC.
- Further work is needed to tidy up our logging helper classes
> EID-1380 - Log when the Translator signs and what with

- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/resources/HubResponseTranslatorResource.java
- Log the hash as soon as the information is available after the call to the VSP.
- Do this before response generation.
- Then log the response.
> EID-1363: Change hash and response logging order

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/logging/EidasAuthnRequestAttributesLogger.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/configuration/CloudHsmCredentialConfiguration.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/configuration/KeyFileCredentialConfiguration.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/logging/SamlSigningLoggerHelper.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/SamlObjectSigner.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/SamlObjectSignerTest.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/EidasResponseGenerator.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- stub-connector/src/test/java/uk/gov/ida/notification/apprule/EidasResponseValidatorAppRuleTests.java
- Log when each response is signed and specify whether it is being
signed with the CloudHSM or the KeyFile
- Use MDC.remove() rather than MDC.clear() to preserve state of MDC
> EID-1380 - Log when the Translator signs and specify what it is using

- .travis.yml
- build.gradle
- snyk/configurations.sh
- snyk/monitor.sh
- snyk/test.sh
~~This PR is not ready to be merged. There's a technical issue on Snyk's end. Despite this repo being open source they're still imposing a limit of 200 tests per month on us (opensource projects should be unlimited). I have an ongoing support request with them. The approach and the code can still be reviewed however.~~
Snyk have kindly given us unlimited tests until they've resolved the issue, so this looks like it's ready for review.
Snyk doesn't play very nicely with gradle sub-projects that use
configurations like we do. As such we can't use the Github integration.
We _can_ use the CLI however with Travis to get a similar result.
We can't test individual sub projects, only the gradle configurations.
The configurations to be tested are defined in one place, `snyk/configurations.sh`
so …
> EID-1381 Integrate with Snyk

- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/SamlParser.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/SamlParserTest.java
Instead of creating our own SAML parser and having to worry about the
security features that have to be enabled, delegate to litsec's
`ObjectUtils` class which correctly uses the OpenSAML parser pool which
should always be securely configured.
I've left the tests for XML attacks in place for reassurance.
> BAU: More secure SAML parsing

- stub-connector/Dockerfile
- stub-connector/build.gradle
stub-connector requires CloudHSM libraries and can no longer be built
using the shared Dockerfile.
> Build stub-connector using own Dockerfile

- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/ResponseAssertionDecrypter.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/StubConnectorApplication.java
We're using the `SAMLObjectDecrypter` to decrypt the Response assertions
that come back from the proxy node. Since stub connector uses the HSM to
decrypt, the class needs to have a workaround enabled.
The `SAMLObjectDecrypter` source has this to say:
If using a HSM it is likely that the SunPKCS11 crypto provider is used. This provider does not have support for
OAEP padding. This is used commonly for XML encryption since
{@code http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p} is the default algorithm to use for key encryption. This
class has a workaround for this limitation that is enabled by setting the {@code pkcs11Workaround} flag.
> BAU: Enable PKCS11 workaround for stub connector

- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/ResponseAssertionDecrypter.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/StubConnectorApplication.java
This reverts commit 8ca20e3ba2d6580e99c5936d6c8199538e25d249.
> Revert "BAU: Enable PKCS11 workaround for stub connector"

- proxy-node-shared/src/main/java/uk/gov/ida/notification/configuration/CloudHsmCredentialConfiguration.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/ResponseAssertionDecrypter.java
The stub-connector doesn't seem to know to use the Cavium provider when
it decrypts Assertions from the translator so let's force it.
> BAU: Force ResponseAssertionDecrypter to use Cavium provider

- doc/adr/20190320-additional-tracing.md
- doc/adr/20190320-anti-affinity.md
We're adding some extra complexity into the system, in order to mitigate
some of the risks outlined by NCSC. We should be documenting the
decisions and approaches we have taken, in order to reflect on these in
the future and keep the context alive.
- Read through, seek sense
> Add Tracibility and Anti-Affinity ADRs

- proxy-node-gateway/src/dist/config.yml
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayConfiguration.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/EidasSamlParserResponseExceptionMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/ExceptionToErrorPageMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/ExceptionToSamlErrorResponseMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/FailureResponseGenerationExceptionMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/GenericExceptionMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/SessionMissingExceptionMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/VerifyServiceProviderRequestExceptionMapper.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/EidasAuthnRequestAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HubResponseAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/base/GatewayAppRuleTestBase.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/GatewayAppRule.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/views/ErrorPageView.java
- proxy-node-shared/src/main/resources/uk/gov/ida/notification/views/error-page.mustache
Redirect to a static error page hosted in verify-frontend when a failure SAML message cannot be generated and returned to the connector node that sent the authn request.
For the time being, we will redirect to the current error page (hosted by the proxy node) if no redirect URL has been configured. This is to enable the app run locally. In the future, once we have a local env, we will want to make the redirect URL mandatory and have the startup script host a static local error page to redirect to.
> EID-1412: Handle internal errors - redirect to static error page

- build.gradle
This fixes [CVE-2018-12545](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-12545).
Build 185 bumps dropwizard from 1.3.8 to 1.3.9. It also condenses all
the saml-libs into one saml-lib, hence the reduced number of deps.
The other thing this commit does it removes the dependency on
common-test-utils. Firstly, the version specified ("${utils_version}"),
doesn't actually exist and gradle was falling back to the version
specified in the saml-metadata-binding library (46). Secondly, the tests
compile and run fine without it so I've dropped it.
> BAU Bump saml-libs to saml-lib:3.4.2-185

- proxy-node-acceptance-tests/features/proxy_node.feature
- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
As part of getting the acceptance tests to run in the release pipeline
it'd be useful if the ones we have ran green. These tests need more work
in general but that's out of scope for this ticket.
The error page we serve from the frontend does not include the http
status code. Also selenium does not currently support access to the
status code of a request, so the error page test has been changed to
just check the content.
> EID-1384 Tweak acceptance tests

- proxy-node-acceptance-tests/features/support/env.rb
This avoids possible confusion with the verify hub.
This variable is useful for our acceptance tests running in the deploy
pipeline. It allows us to use the selenium hub running in the tools
account rather than spinning up a new one each time.
> EID 1384 Rename selenium hub env variable

- build.gradle
We want to standardise compile and runtimes to OpenJDK 11.
This PR will use the latest `verify-saml-libs`, compiled with with OpenJDK 11.
> use latest verify-saml-libs, built with OpenJDK 11

- proxy-node-acceptance-tests/features/proxy_node.feature
Add three error scenario tests to acceptance suite. We want to observe them pass on the proxy node promotion pipeline.
> Reinstate ignored Proxy Node acceptance tests

- proxy-node-gateway/build.gradle
the public facing gateway service does not do saml processing so it should not require the opensaml libraries.
These are largely set via transitive dependencies within the `proxy-node-shared` module.
You can check gateway dependencies using:
`./gradlew proxy-node-gateway:dependencies --configuration compile`
This PR removes these dependencies, reducing attack surface area available via the gateway classpath.
> Remove opensaml dependencies from gateway

- proxy-node-acceptance-tests/features/proxy_node.feature
- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
- proxy-node-acceptance-tests/run-staging-tests.sh
- Rename some acceptance tests for clarity
- Fix the script which runs tests against staging
- Remove an unneeded step in an error scenario
This PR will make [the promotion pipeline](https://ci.tools.verify.govsvc.uk/teams/main/pipelines/promotion) go green 🤞
> Fix Proxy Node acceptance tests

- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/ReceiveResponseResource.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/views/ResponseView.java
- stub-connector/src/main/resources/uk/gov/ida/notification/stubconnector/views/response.mustache
To help in tracking a user journey through logs, surface the eidas request id in `stub-connector` logs  and result page.
> show eidas request id in stub connector result page

- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/SendAuthnRequestResource.java
We don't have any acceptance tests that assert the RelayState sent from stub-connector to Proxy Node gateway is returned.
This PR _should_ 🙏 send the stub-connector as RelayState to Proxy Node.
If it does, another PR will amend acceptance tests.
> send the stub connector session id as RelayState to Proxy Node

- .travis.yml
- build.gradle
For all prod builds we need to ensure that the Proxy Node pulls dependencies from Artifactory instead of Bintray. Travis still needs to access Bintray as it cannot access Artifactory.
- Added `VERIFY_USE_PUBLIC_BINARIES` flag which is set to `true` for Travis builds
- If the flag is `false` (default), set `gradle` to pull dependencies from Artifactory
- Exclude unnecessary transitive dependencies
- Update libraries to latest versions
> EID-1490: Switch to pulling dependencies from Artifactory

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/saml/validation/components/AssertionConsumerServiceValidator.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/BaseExceptionToErrorPageMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/ExceptionToSamlErrorResponseMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestExceptionMapperResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/EidasAuthnRequestResourceTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/HubResponseResourceTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/configuration/CloudHsmCredentialConfiguration.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/configuration/KeyFileCredentialConfiguration.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/ResponseAssertionDecrypter.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/SamlObjectSigner.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/SamlSignatureValidatorFactory.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/ProxyNodeLogger.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/SamlObjectSignerTest.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/ProxyNodeLoggerTest.java
- proxy-node-test/src/main/java/uk/gov/ida/notification/apprule/rules/TestMetadataResource.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/resources/HubResponseTranslatorResource.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/ReceiveResponseResource.java
- stub-connector/src/test/java/uk/gov/ida/notification/apprule/EidasResponseValidatorAppRuleTests.java
Make logging more consistent by always using the same logger
Summary of changes:
- Changes to the ProxyNodeLogger to make it easier and more consistent to use
- Replace all instances of `java.util.logging` and `SLF4J` loggers with the new ProxyNodeLogger
- Remove `ProxyNodeLogger` from all constructors as it can be easily instantiated within any class
- Test MDC params by capturing the log event and extracting the MDC param map
> EID-1502: Use ProxyNodeLogger everywhere

- proxy-node-vsp-config/Dockerfile.internal
apt-get is interactive by default and requires either an explicit "yes"
or the `-y` flag.
> Fix Dockerfile build

- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/EidasAuthnRequestAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/EidasAuthnRequestResourceTest.java
Use the ProxyNode Journey ID for the relay-state when sending request to the hub.  This will help us track journeys across microservice boundaries.
Get the ProxyNode Journey ID from the http session when handling authn requests and put it in the relay-state of the saml form that sends the request to the hub.
Update tests accordingly.
Co-authored by: Karol Gancarz <karol.gancarz@digital.cabinet-office.gov.uk>
> EID-1506 Use ProxyNode Journey ID for the relay-state when sending requests to the hub

- proxy-node-acceptance-tests/features/proxy_node.feature
- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
- proxy-node-acceptance-tests/run-staging-tests.sh
New Acceptance tests for Proxy Node journeys, to show the correct error pages based on [this Hub PR](https://github.com/alphagov/verify-hub/pull/294)
> Acceptance tests for EID-1517

- chart/templates/saml-metadata.yaml
In eIDAS world the entityID has to match the Metadata URL
> BAU: Make Proxy Node metadata entityID match the URL

- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/IstioHeaderMapperFilter.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/ProxyNodeLoggingFilter.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/IstioHeaderMapperFilterTest.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
In order to validate that we are shipping Istio tracing headers among our microservices, we want to temporarily log a set of known Istio tracing headers on resource egress.
The change is in `IstioHeaderMapperFilter.java`.
Also ensure multi-valued Istio headers are sent.
> 🙈Temporarily log istio tracing headers

- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/EidasAssertionBuilder.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/EidasResponseBuilder.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/logging/EidasResponseAttributesHashLoggerParameterizedTest.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/saml/HubResponseTranslatorTest.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/ReceiveResponseResource.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/views/ResponseView.java
- stub-connector/src/main/resources/uk/gov/ida/notification/stubconnector/views/response.mustache
- stub-connector/src/test/java/uk/gov/ida/notification/apprule/EidasResponseValidatorAppRuleTests.java
- stub-connector/src/test/java/uk/gov/ida/notification/stubconnector/EidasAuthnRequestContextFactoryTest.java
- Display LOA
- Display attribute names
- Display decoded SAML message to easily verify against the eIDAS spec
- Encrypt assertions in Stub Connector tests
- Slightly refactor `EidasAssertionBuilder` methods to make it easier to understand where LOA is set
Test Connector response page will look like this:
> EID-1530: Add more detail to the Stub Connector response page

- .snyk
- README.md
- eidas-saml-parser/src/dist/config.yml
- proxy-node-gateway/src/dist/config.yml
- proxy-node-translator/src/dist/config.yml
- proxy-node-vsp-config/verify-service-provider.yml
The app logs being sent to Splunk are all in json format which is
processed nicely by Splunk. The access logs however are not.
Here's an example of a request log next to an app log:
> EID-1508 Log requestLogs with logstash-console

- .gitignore
- chart/templates/metadata-signing-cert.yaml
- chart/templates/metadata.yaml
- ci/build/intermediate-certificate-request.yaml
- ci/integration/intermediate-certificate-request.yaml
- ci/prod/intermediate-certificate-request.yaml
updates the metadata config and adds metadata signing cert for the
proxy-node after the CertificateRequest changes to metadata-controller
we now add have a per-cluster root ca ... a per-namespace intermediate
ca and per-instance metadata signing certs.
> Intermediate certs for use with new metadata-controller

- chart/templates/metadata-signing-cert.yaml
I _think_ the tripple hyphen at top of the CertificateRequest is causing a problem where something is interpreting it as a list
> remove trip hyphen from resource header

- .snyk
- chart/templates/translator-deployment.yaml
- chart/values.yaml
- ci/integration/deploy-pipeline.yaml
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/EidasAssertionBuilder.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/EidasResponseBuilder.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/contracts/verifyserviceprovider/TranslatedHubResponseTestAssertions.java
- proxy-node-translator/src/dist/config.yml
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/configuration/TranslatorConfiguration.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/base/TranslatorAppRuleTestBase.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/saml/HubResponseTranslatorTest.java
The eIDAS specification states that a PID should be prefixed with
"{Identifying country nationality code}/{destination country nationality
code}".
This allows a nationality code to be provided via the configuration.
This is a short term solution as it only allows for the proxy node to be
connected to one country.
When we restructure to allow multiple countries this will need
revisiting.
> EID-1532 implement correct pid translation

- .snyk
- build.gradle
- eidas-saml-parser/src/dist/config.yml
- proxy-node-gateway/src/dist/config.yml
- proxy-node-translator/src/dist/config.yml
- proxy-node-vsp-config/verify-service-provider.yml
`io.dropwizard:dropwizard-json-logging` will need to be made
available via artifactory for the build to go green. I think only an admin
can do that.
Setting the requestLog type to 'logstash-console' on its own, done 
in [PR#222](https://github.com/alphagov/verify-proxy-node/pull/222) didn't
work. In fact, it meant that no request logs at all were shipped. I
think this was due to dropwizard not being able to find the correct
type.
Rather than using the `logstash-console` type we can set the layout of the
requestLogs to json, as suggested by the docs: https://www.dropwizard.io/1.3.12/docs/manual/core.html
To do this we need to pull in the `dropwizard-json-logging` module.
This PR also removes the requestLog changes to the VSP. Due to the
new approach requiring a new library, a change would …
> EID-1508: Set requestLog layout to access-json

- build.gradle
- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java
- libs/eidas-saml-parser/pom.xml
- libs/proxy-node-gateway/pom.xml
- libs/proxy-node-shared/pom.xml
- libs/proxy-node-test/pom.xml
- libs/proxy-node-translator/pom.xml
- libs/stub-connector/pom.xml
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/configuration/EidasSamlParserServiceConfiguration.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/configuration/TranslatorServiceConfiguration.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/EidasSamlParserProxyTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/TranslatorProxyTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/IstioHeaderMapperFilter.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/IstioHeaderStorage.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/proxy/ProxyNodeJsonClient.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/IstioHeaderMapperFilterTest.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/proxy/ProxyNodeJsonClientTest.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/StubConnectorApplication.java
Create an IstioHeaderStorage class that uses ThreadLocal to store Istio headers.  Use a request filter to capture the Istio headers on the way in.  Update ProxyNodeJsonClient so that it has access to an instance of IstioHeaderStorage for retrieving the current request’s Istio headers to pass on.  Append Istio headers to response on the way out and clear the headers out of the thread local.
> EID-1487 Send Istio headers with ProxyNodeJsonClient requests

- proxy-node-shared/src/main/java/uk/gov/ida/notification/validations/PEMCertificateValidator.java
- NL cert comes in at just over 2070 bytes.
- Increase upper bound on cert size to 4096, previous bound was 2048.
> Fix to permit NL cert to pass size validation

- chart/templates/gateway-deployment.yaml
- chart/templates/stub-connector-deployment.yaml
Instead of creating new containers for them - mount them in the existing gateway and connector containers
> BAU: Mount metadata volumes directly

- ci/build/release-pipeline.yaml
Drafts don't have tags. This means the `package` step fails to bump the
version number:
```
generate-chart-version
11:38:54 bumping release number...
11:38:54 cat: can't open 'release/tag': No such file or directory
```
> Use GitHub release pre-releases

- chart/templates/hub-egress-destination-rules.yaml
- chart/templates/hub-egress-virtual-service.yaml
Fix an issue with overlapping rules getting in each other's way.
> Limit scope of hub egress rules to current namespace only.

- build.gradle
- snyk/configurations.sh
- stub-connector/build.gradle
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/SendAuthnRequestResource.java
- stub-connector/src/main/resources/uk/gov/ida/notification/stubconnector/views/startpage.mustache
Adds an extra error scenario to the stub-connector for an invalid
signature. It uses the test private key from the dev-pki repo. This key
does not match the certificate the proxy-node ESP will be using and so
should result in an invalid signature response.
Also updates the homepage and some styling to differentiate between
valid and invalid journeys.
> EID-1483 Extend stub-connector authn request error scenarios

- proxy-node-acceptance-tests/features/proxy_node.feature
- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
The failure scenarioes the stub-connector is able to generate has
changed.
> EID-1483 Update acceptance tests for new stub connector failure

- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
Need to convert the string to a symbol or the hash just returns `nil`.
> EID-1483 Update acceptance tests again

- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
**Sigh**
Cucumber wasn't recognising the changed scenario definitions and
linking them with a user step. Hopefully changing to use a regex will
help.
> EID-1483 Update acceptance tests to use regex

- chart/templates/esp-network-policy.yaml
- chart/templates/esp-redis-network-policy.yaml
- chart/templates/gateway-redis-network-policy.yaml
- chart/templates/translator-network-policy.yaml
- chart/templates/vsp-network-policy.yaml
We're deploying these _n_ times to the same namespace so we need to
include something extra in the NetworkPolicy names.
> BAU: Fix NetworkPolicy name collisions

- chart/templates/metrics.yaml
This configures Istio to record HTTP request metrics which include the
request path as a label.
The way this works is: we have a `metric`, which is sent to a
`handler` by a `rule`.
The `metric` records which dimensions from the underlying HTTP event
we wish to record.  The requestcountbypath metric in this commit is
based on the builtin requestcount metric in the istio-system
namespace (see `kubectl -n istio-system get metrics`), but with an
additional `request_path` dimension.
The `rule` states which events are sent to the `handler`.  In this
case, `promhttpbypath` is based on istio-system's `promhttp` rule,
only referring to the requestcountbypath metric instead.  The `match:`
condition states that we will send http events which were not
initiated by kube-probe (which presumably is …
> Add metrics from istio

- chart/templates/metrics.yaml
To avoid name clashes between different Proxy Node deployments in the same namespace
> BAU: Deploy a separate set of metrics resources for each PN deployment

- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/base/EidasSamlParserAppRuleTestBase.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/validations/Base64NotBlankValidator.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/validations/ValidBase64Xml.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/validation/EidasSamlParserRequestValidationTests.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/validations/HubResponseTranslatorRequestValidationTests.java
Countries using CEF reference connector don't include an XML declaration
at the beginning of Authn requests. This causes requests to fail
validation in the gateway.
This changes the validator to not check for the declaration, and instead
does the minimum of checking the decoded Base64 is not blank. If the XML
is actually not valid we'll find out later as it works its way through
the system.
> BAU Remove xml tag check from validation

- proxy-node-shared/src/test/java/uk/gov/ida/notification/contracts/verifyserviceprovider/TranslatedHubResponseTestAssertions.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
The UK's ISO code is actually (confusingly) GB
Source:
https://www.gov.uk/government/publications/iso-country-codes--2
> 🇬🇧🇪🇺 Use UK's ISO code (GB) for Proxy Node

- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/SendAuthnRequestResource.java
The `/InvalidSignature` endpoint on stub-connector seems to create an HSM `CN_NIST_AES_WRAP` event.
We want to check whether the `stub-connector` or `esp` is generating this event.
This PR creates a new endpoint, `/test1`, that is same as `/InvalidSignature` except it does not call gateway.
If event still occurs then the stub-connector must be generating it, which would be nuts!
> A test endpoint for testing out HSM alerts

- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/HubResponseResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/HubResponseResourceTest.java
Invalidate the http session after a successful egress from Gateway to the Government Service.
> Invalidate a http session on a successful response from Hub

- build.gradle
- libs/eidas-saml-parser/pom.xml
- libs/proxy-node-gateway/pom.xml
- libs/proxy-node-shared/pom.xml
- libs/proxy-node-test/pom.xml
- libs/proxy-node-translator/pom.xml
- libs/stub-connector/pom.xml
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/ExceptionToSamlErrorResponseMapper.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/HubResponseResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/SamlResponseExceptionMapperResourceRuleTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/HubResponseResourceTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/SamlFormViewBuilder.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/views/SamlFormView.java
- proxy-node-shared/src/main/resources/uk/gov/ida/notification/views/saml-form.mustache
- proxy-node-shared/src/test/java/uk/gov/ida/notification/SamlFormViewBuilderTest.java
Copy and paste the required styles from the Verify version of these pages.
Remove the 'submitText' parameter from the template, the view that uses the template and anything else affected by the demise of the 'submitText' parameter.
Actually using the full stylesheets would require all sorts of extra work for a page that nobody is going to see unless they've disabled JavaScript so we can use inline styles here because rules need to be applied sensibly.
> EID-1542 Apply GOV.UK style and wording to the JavaScript disabled 'Continue' page

- chart/templates/gateway-ingress-certificate.yaml
- chart/templates/stub-connector-ingress-certificate.yaml
Following the upgrade of cert-manager to 0.11 the api groups changed. This
brings them into alignment.
> Update the api groups of certificate resources.

- ci/build/build-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
We (autom8) want to be able to block access from the public internet to
the Harbor API. Previously we had done this by implementing a IP
safelist. Given some changes we're expecting to make to Istio we will be
unable to see the original IP of the user at the point that our current
safelist performs its checks.
We have decided to block API access entirely (except from within the
cluster).
Our `concourse-harbor-resource` now defaults to using the internal
service to talk to the Harbor API so all we need to do is remove the
explicit setting of `harbor.url`.
> Use the internal service for the Harbor API

- proxy-node-gateway/src/main/java/uk/gov/ida/notification/MetricsUtils.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/HubResponseResource.java
Currently, the prometheus counters aren't getting initialised
correctly.  If you look at `verify_proxy_node_requests_total` in
Grafana's explore view, you see that counters start from 1, when the
first request happens, not 0, when the app starts.  This means that we
will be missing requests from our count of requests (and of successful
requests).
The problem is less pressing for the response counters, because the
first time *any* counter is accessed, they *all* get initialised.
I think this is because the counters are being created in static
initialisers in MetricUtils.  When do static initialisers run?  It's
complicated, but section 12.4 of the standard is the authority [1].
In particular, static initialisers run when the class is initialised,
which can happen when:
- a static field is …
> Initialise prometheus counters correctly

- chart/templates/metrics.yaml
These istio metrics were originally created in #310 and worked
provided you only had a single helm release per namespace.  However
because it didn't include appropriate `{{ .Release.Name }}` scoping in
the resource names, it completely blocked the ability to deploy
multiple instances per namespace.
That problem was fixed in #322, which changed the resource names to
include `{{ .Release.Name }}` as appropriate.  However it didn't
update references to those resource names, nor did it update the name
of the underlying prometheus metric.  This means that the istio
metrics from #310 aren't currently being recorded at all.
This commit fixes the resource references to actually point at each
other, and also adds the `{{ .Release.Name }}` to the prometheus
metric name.  Hopefully, once this is …
> fix istio metrics to actually work

- ci/prod/dashboard.yaml
Dashboards created in [GSP Verify Grafana](https://grafana.london.verify.govsvc.uk) are ephemeral. Defining a dashboard as kubeyaml persists them.
This PR is step 1 in proving this persistence.
We want a single dashboard for the `verify-proxy-node-prod` namespace, so this`ConfigMap` deployment is defined in `ci/prod` only. As a result there is no helm templating.
The name of the dash definition, `verify_proxy_node_prod_dashboard.json` must be global to the cluster.
Also, please don't consider the dashboard json in this PR - this will be updated susequently.
> A simple Grafana dashboard for the Proxy Node

- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- pre-commit.sh
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/istio/IstioHeaderMapperFilter.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/logging/ProxyNodeLogger.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/logging/ProxyNodeLoggingFilter.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/logging/ProxyNodeMDCKey.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/ProxyNodeLoggerTest.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
https://govukverify.atlassian.net/browse/EID-1761
Tidy up Proxy Node error logging, to remove fields `EXCEPTION_STACKTRACE`, `EXCEPTION_MESSAGE` and `LOG_LOCATION`, to produce an error event like:
````
{
"exception": "error message and stack trace ...",
"level": "WARN",
"logger": "uk.gov.ida.notification.shared.logging.ProxyNodeLogger",
"thread": "dw-74 - POST /SAML2/SSO/Response/POST",
"message": "Error whilst contacting URI [http://localhost:51529/SAML2/SSO/Response/POST]",
"HUB_REQUEST_ID": "a hub request id",
"PROXY_NODE_JOURNEY_ID": "_af111e686076206535861fc6c6d2597d",
"RESOURCE_PATH": "http://localhost:51529/SAML2/SSO/Response/POST",
"SESSION_ID": "node05yd8shxs9kck1c55vwpih391b2",
"REFERER": "",
"EIDAS_REQUEST_ID": "_95338268-84ae-427b-89cf-55b81bcb4181",
"timestamp": 1573223548800 …
```
> EID-1761 Improve Proxy Node error logging

- chart/templates/_helpers.tpl
- ci/build/build-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
- proxy-node-acceptance-tests/run-staging-tests.sh
- proxy-node-gateway/src/test/resources/metadata/test-proxy-node-metadata.xml
- proxy-node-shared/src/test/resources/metadata/test-metadata.xml
- stub-connector/src/test/resources/metadata/test-stub-connector-metadata.xml
Reverts alphagov/verify-proxy-node#371
We are still building our build pipeline from master because our verify-cluster-config PRs didn't build correctly, see https://ci.london.verify.govsvc.uk/teams/proxy-node-build/pipelines/configure-namespace/jobs/apply/builds/14.
We want to restore master to its original hostnames, to make the build pipeline green again.
> 🙀Revert "EID-1823 Update urls for multi-country build release"

- ci/build/build-pipeline.yaml
- proxy-node-vsp-config/Dockerfile
We want to update our build pipeline to refer to the new release branch.
We did this before but didn't branch off the release branch and then merge onto it using the GSP process. This is a take 2.
> Update build namespace to refer to release branch

- ci/build/build-pipeline.yaml
- ci/integration/deploy-pipeline.yaml
- ci/prod/deploy-pipeline.yaml
- ci/prod/killswitch-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
- ci/sandbox/deploy-pipeline.yaml
- ci/sandbox/killswitch-pipeline.yaml
The latest version of the github resource doesn't need this (since
alphagov/gsp#378).  Instead the process is to add your GPG key to
GitHub and get GitHub to verify the signature; we only need to
validate the signature on the GitHub merge commit against the GitHub
web flow key.
Note that if we can get rid of commit_verification_keys from all our
pipelines, we can also merge alphagov/gds-trusted-developers#111 so
that we no longer have to faff with GPG keys in that repository when
people join teams that commit to GSP projects.
This also bumps the task-toolbox and github-resource references to use
the tag provided by GSP in the `concourse` secret.
> remove commit_verification_keys

- ci/build/build-pipeline.yaml
Refer to the release branch when building and releasing on the "legacy" build pipeline.
> EID-1822 Refer to release branch on build and release pipeline

- ci/build/build-pipeline.yaml
- ci/integration/deploy-pipeline.yaml
- ci/prod/deploy-pipeline.yaml
The quotes in the regex were causing an "found unknown escape character" message in configure namespace pipelines.
This is a fix to https://github.com/alphagov/verify-proxy-node/pull/385
Other examples that do not use quotes are: https://github.com/alphagov/gsp/search?q=tag_filter&unscoped_q=tag_filter
> EID-1822 Amend regex to remove quotes

- ci/build/build-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
- eidas-saml-parser/build.gradle
- proxy-node-gateway/build.gradle
- proxy-node-translator/build.gradle
- stub-connector/build.gradle
[Integration tests are failing](https://ci.london.verify.govsvc.uk/teams/proxy-node-build/pipelines/build-release/jobs/build-proxy-node/builds/32) to correctly compare the string contents of a `favicon.ico` to expected output.
The Amazon Coretto Docker image is not setting file-encoding to utf-8, which presumably was set in openjdk images.
* Set the file encoding to utf-8 in `GRADLE_OPTS` to allow the tests to pass
* Also set the file-encoding of the built applications to use utf-8
This fix has been tested in sandbox, and fixes the pipeline in that cluster.
-----------
This was a useful test failure as it surfaced an encoding issue that might cause issues in production.
> EID-1822 build and run with utf8 file encoding

- ci/build/build-pipeline.yaml
Adds the build-triggering git commit short_ref to the [github release](https://github.com/alphagov/verify-proxy-node/releases).
This will indicate the **branch** that the release should be associated with.
**Why:**
The latest release, https://github.com/alphagov/verify-proxy-node/releases/tag/v1.119, from the release branch, picked a short ref by default from master. The short ref should be [this commit from the branch](https://github.com/alphagov/verify-proxy-node/commit/d0ff6d95ac390314d64c1a07cd304787758e09f7).
Co-authored-by: George Lund <george.lund@digital.cabinet-office.gov.uk>
> EID-1822 Add short_ref of commit to release to associate with branch

- .snyk
- build.gradle
- proxy-node-acceptance-tests/Gemfile
- proxy-node-acceptance-tests/Gemfile.lock
* Fix for https://snyk.io/vuln/SNYK-JAVA-COMNIMBUSDS-536068.
* Ignore the vulnerability https://snyk.io/vuln/SNYK-JAVA-CAJULIUSDAVIES-30073 until Dec 15, as there is no release yet that addresses it.
* Patch Gemfile & proxy-node-acceptance-tests/Gemfile.lock to reduce vulnerabilities
> 🍒SNYK cherry-pick of snyk updates from master to release

- ci/integration/smoke-test.yaml
Get the `tests-image` resource  to use in the task, otherwise the [pipeline fails](https://ci.london.verify.govsvc.uk/teams/proxy-node-integration/pipelines/configure-namespace/jobs/apply/builds/24).
> EID-1854 get the tests-image resource to use in smoke test task

- ci/build/build-pipeline.yaml
The test connector in particular is creating handles to HSM keys which is contributing to us going over quota.
We want to reap these key handles by regularly deleting the test release.
> EID-1872 Delete test release nightly & before test

- .snyk
- chart/templates/esp-deployment.yaml
- chart/templates/esp-redis-deployment.yaml
- chart/templates/gateway-deployment.yaml
- chart/templates/gateway-redis-deployment.yaml
- chart/templates/stub-connector-deployment.yaml
- chart/templates/translator-deployment.yaml
- chart/templates/vsp-deployment.yaml
Replaces https://github.com/alphagov/verify-proxy-node/pull/420
I'm not 100% sure this will work, looking for opinions.
We release the apps nightly on a trigger in Concourse. However kapp's
behaviour is to only release stuff if it's changed. If nothing has
changed, kapp won't actually re-deploy apps for us. You can see an
example of this here.This may be
contributing to the issue with the HSM retaining keys.
We should be able to annotate these deployments with a timestamp. This
will mean that kapp detects a change in the app when in renders the
manifest and will redeploy it.
> Eid 1873 annotate deployments so they're rolled nightly

- ci/prod/dashboard.yaml
Monitor open sessions so as to keep an eye on resource leaks.
The last PR had (I think) an errant `id` field that was never supposed to be there (see <https://grafana.com/docs/grafana/latest/administration/provisioning/#making-changes-to-a-provisioned-dashboard>).
The same thing applied ok in the Sandbox so hopefully this will be ok.
https://govukverify.atlassian.net/browse/EID-1875
> EID-1875 HSM monitoring on the eIDAS dashboard

- ci/build/build-pipeline.yaml
`gradlew` is not in the path, so we need to call it with a relative path
instead.
> EID-1806 Call `gradlew` properly

- ci/build/build-pipeline.yaml
Concourse didn't like the previous version. I've tested this locally and
it works.
> EID-1806 Fix structure of args

- Dockerfile
- cloudhsm/Dockerfile
- cloudhsm/jdk-jce-image/Dockerfile
- proxy-node-translator/build.gradle
- stub-connector/build.gradle
There is a new major version of the [cloudhsm client software](https://docs.aws.amazon.com/cloudhsm/latest/userguide/client-history.html)
I was looking into this to see if they had released a fix to the issue
we're experiencing with the hsm retaining temporary keys. It looks like
this version does not fix that issue, but it's still probably a good
idea to upgrade.
I've applied this change to the sandbox without any issues.
> BAU - Bump cloudhsm tools to 3.0.0

- Dockerfile
- cloudhsm/Dockerfile
- cloudhsm/jdk-jce-image/Dockerfile
- proxy-node-translator/build.gradle
- stub-connector/build.gradle
This is a cherry pick of a commit just merged to the release branch. Pulling the change into master.
There is a new major version of the [cloudhsm client software](https://docs.aws.amazon.com/cloudhsm/latest/userguide/client-history.html)
I was looking into this to see if they had released a fix to the issue
we're experiencing with the hsm retaining temporary keys. It looks like
this version does not fix that issue, but it's still probably a good
idea to upgrade.
I've applied this change to the sandbox without any issues.
> 🍒⛏BAU - Bump cloudhsm tools to 3.0.0

- proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/ExceptionToSamlErrorResponseMapper.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/SamlResponseExceptionMapperResourceRuleTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestExceptionMapperResource.java
When there is an error in response from translator to gateway, for a subset of errors we'll try to build an error saml response, by calling translator again to generate a signed error saml response.
This is handled by the translator `/generate-failure-response` resource.
We do not handle the case where this resource throws an ApplicationException - and a standard dropwizard error page is rendered.
You can see this being played out in this journey: https://gds.splunkcloud.com/en-GB/app/search/search?sid=1576743919.185861
This PR is to redirect to the hub error page in this scenario.
https://govukverify.atlassian.net/browse/EID-1876
> EID-1876 Hub error page if can't build error SAML

- ci/build/build-pipeline.yaml
- ci/integration/deploy-pipeline.yaml
- ci/prod/deploy-pipeline.yaml
- ci/prod/killswitch-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
- ci/sandbox/deploy-pipeline.yaml
- ci/sandbox/killswitch-pipeline.yaml
See https://github.com/alphagov/gsp/pull/858
Cherry-pick of #435 to release/single-country-legacy
> Replace concourse.k8s.io API group with concourse.govsvc.uk

- .snyk
- chart/templates/_helpers.tpl
- chart/templates/esp-deployment.yaml
- chart/templates/stub-connector-deployment.yaml
- chart/values.yaml
- ci/build/build-pipeline.yaml
- ci/build/test-pki.yaml
- ci/integration/test-pki.yaml
- ci/sandbox/test-pki.yaml
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/ResponseAssertionDecrypter.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/SignatureSigningParametersHelper.java
- stub-connector/build.gradle
- stub-connector/src/dist/config.yml
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/ConnectorNodeCredentialConfiguration.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/StubConnectorApplication.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/StubConnectorConfiguration.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/metadata/MetadataGenerator.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/MetadataResource.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/SendAuthnRequestResource.java
- stub-connector/src/main/resources/connector_template.xml.mustache
- stub-connector/src/main/resources/uk/gov/ida/notification/stubconnector/views/startpage.mustache
- stub-connector/src/test/java/uk/gov/ida/notification/apprule/EidasResponseValidatorAppRuleTests.java
- stub-connector/src/test/java/uk/gov/ida/notification/apprule/StubConnectorAssetsAppRuleTests.java
- stub-connector/src/test/java/uk/gov/ida/notification/apprule/base/StubConnectorAppRuleTestBase.java
- stub-connector/src/test/java/uk/gov/ida/notification/stubconnector/metadata/MetadataGeneratorTest.java
TLDR; The Stub Connector represents a stub country. It should not have its saml signing coupled to an HSM key.
Cherry pick from the release branch onto master, which is where we're doing multi-country dev.
The Stub Connector currently has its metadata certs+keys generated via the verify-metadata-controller, and the saml signing key is held in the HSM.
Every SAML request from stub connector is currently signed by a key in the CloudHSM. This was done as a convenience as the truststore for this signing is also generated via verify-metadata-controller, and easily made available to the ESP (the service that reads the connector metadata and then validates it against the truststore).
We want to model a a stub country that has its own PKI completely outside the HSM. The eventual goal is to run …
> 🍒EID-1877 Decouple Stub Connector from the HSM

- .snyk
- chart/templates/esp-deployment.yaml
- chart/templates/esp-redis-deployment.yaml
- chart/templates/gateway-deployment.yaml
- chart/templates/gateway-redis-deployment.yaml
- chart/templates/stub-connector-deployment.yaml
- chart/templates/translator-deployment.yaml
- chart/templates/vsp-deployment.yaml
Add a timestamp annotation on the spec template during helm templating.
This will mark the pod referenced in the deployment as changed, and k8s should reconcile with a redeploy.
This is required for nightly rolling.
> EID-1873 add timestamp annotation on pod

- proxy-node-acceptance-tests/Gemfile.lock
[CVE-2019-16782](https://github.com/advisories/GHSA-hrqr-hxpp-chr3)
> BAU Upgrade rack to fix security warning

- .snyk
- build.gradle
- snyk/configurations.sh
The snakeyaml vulnerability isn't going away anytime soon. You can read
a short summary at the added link.
We no longer used the soft_hsm configuration so this cleans up a little.
It also sorts the list of configurations snyk tests to make it easier to
check the correct ones are being tested.
> EID-1881: Investigate snakeyaml

- ci/build/build-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
YAML will take `true` as a boolean instead of a string "true".
> Ensure environment variables are set to strings

- ci/build/build-pipeline.yaml
This was fine when we just had two put steps - one for each image.
Now we build and put for each image separately. So we need to ensure build
happens before that image's put.
> Serialise build-cloudhsm

- ci/build/build-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
Redoes reverts commit 920530e7634355f32a8536d8c85ba38bad07b7d2 in a different
way.
Continue doing things in parallel, but be careful about build steps being done
before we put the result to the image repository. Also ensure that the output
directory names are unique to avoid one image being built and pushed to a
different image's repository.
> Try to fix parallel stuff in pipeline

- ci/build/build-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
From the docker-image/harbor resources which we don't use anymore.
> ci: Remove skip_download params

- ci/build/build-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
format parameter defaults to rootfs
> no rootfs param for alpine-image with registry-image resource

- ci/build/build-pipeline.yaml
- ci/sandbox/build-pipeline.yaml
Error was: `/bin/ash: syntax error: unexpected redirection`
> Fix Dockerfile creation for chart package

- .snyk
Ignore Snyk reported CVE https://snyk.io/vuln/SNYK-JAVA-ORGCRYPTACULAR-543303 until repo owners release 1.2.4.
Tested locally with `./snyk/test.sh`
> 🍒ignore SNYK-JAVA-ORGCRYPTACULAR-543303 temporarily

- chart/templates/gateway-ingress-virtual-service.yaml
- chart/templates/metatron-ingress-virtual-service.yaml
- chart/templates/stub-connector-gateway-egress-service-entry.yaml
- chart/templates/stub-connector-ingress-virtual-service.yaml
ServiceEntry, DestinationRule, and VirtualService resources default to "all namespaces". We need a per-namespace configuration.
Pre-requisite of the dev-namespaces work.
> Isolate istio resources to current namespace only.

- ci/integration/principal.yaml
- ci/integration/smoke-test.yaml
We no longer put to the harbor repository.
The full-URI-to-pull-across-namespace trick is borrowed from @bjgill in DCS.
> Fix the last remaining harbor usage

- local-startup/Dockerfile
- local-startup/docker.env
The way that stub-connector got it's signing credentials had changed
slightly which prevented it from starting up.
Also bumps the gradle version the images are built on to match the new
gradle syntax being used.
> BAU: Fix docker local-startup

- local-startup/docker.env
The request to the URL is made from the outside the docker network on
the host so there's no way to resolve the hostname. Setting it localhost
fixes this.
> BAU: Fix stub-connector ACS for docker local startup

- .snyk
It's believed we're not effected by the vulnerability. This adds a link
to the jira ticket for more context.
> EID-1921: 🍒 Add comment to snyk file for cryptacular

- .snyk
It's believed we're not effected by the vulnerability. This adds a link
to the jira ticket for more context.
> EID-1921: Add comment to snyk file for cryptacular

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestEidasSamlResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/EidasSamlParserProxyTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/EidasAuthnRequestResourceTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/HubResponseResourceTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/session/TestGatewaySessionDataValidator.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/EidasSamlParserResponse.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/session/storage/RedisStorageService.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/saml/HubResponseTranslatorTest.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/validations/HubResponseTranslatorRequestValidationTests.java
We no longer need to pass the encryption certificate around as it's possible to get the information from Metatron.
Remove connectorEncryptionPublicCertificate from EidasSamlParserResponse.
Update any use of EidasSamlParserResponse so that code will compile.
Update tests so that they reflect new DTO.
*NOTE* this depends on eid-1836 as it's branched from there - there's some dependency between because of the Redis change in eid-1836
> EID-1837 Clean up DTOs used between Gateway and ESP

- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/base/EidasSamlParserAppRuleTestBase.java
Some time ago, builds stopped building.  The test that fails doesn't fail locally or when Travis runs it.  This suggests some kind of race is going on and the wrong thing wins in the pipeline.  It looks like it's the mockatron that's providing the null pointer exceptions when it should be providing port numbers so I've changed the order in which the RuleChain is executed to see if that helps.
> BAU Un-break the broken build

- ci/integration/smoke-test.yaml
- ci/sandbox/test-pki.yaml
- proxy-node-acceptance-tests/features/smoke/integration.feature
- proxy-node-acceptance-tests/features/smoke/nl-request.feature
- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
Cherry-pick of release branch; Add Netherlands smoke tests, see https://github.com/alphagov/verify-proxy-node/pull/415
> 🍒EID-1855 NL smoke test

- proxy-node-vsp-config/verify-service-provider.yml
Use the same env var for the "three" truststores as it's really the same truststore
> BAU: Fix VSP config

- chart/values.yaml
- ci/sandbox/build-pipeline.yaml
We want to use `signin.service.gov.uk` for Proxy Node.
We're testing this on sandbox.
We need to merge a PR onto the sandbox branch for the `configure-namespace` pipeline to accept the merge.
> set domain to sandbox.signin.service.gov.uk

- local-startup/docker.env
The `/metatron/` path fragment is added in the ESP and translator by the
functions that build the clients.
> BAU: Fix Metatron URL for docker local startup

- .snyk
- build.gradle
Extend SNYK-JAVA-CAJULIUSDAVIES-30073 ignore, and upgrade org.cryptacular:cryptacular
> fix snyk-reported vulns

- chart/templates/metadata-signing-cert.yaml
- chart/templates/metadata.yaml
- ci/build/intermediate-metadata-certificate-request.yaml
This is part 1 of [new test certificate chain for multi country proxy node build environment](https://govukverify.atlassian.net/browse/EID-1953) 
- Create metadata signing chain for build namespace
see for details:
https://github.com/alphagov/verify-proxy-node/blob/149d4fa9ff31722586d5070d6a9c3b24c2c390d3/doc/metadata_signing.md
Co-authored-by: Phillip Miller <phillip.miller@digital.cabinet-office.gov.uk>
> EID-1953 Create New Metadata Signing Chain

- build.gradle
the github resource on our build pipeline https://ci.london.verify.govsvc.uk/teams/eidas-proxy-node-build/pipelines/build-release/jobs/build-proxy-node/builds/66  is not taking 2 approvals from trusted developers.
This PR is to attempt getting the src again, hoping for success due to a different approval set, or cosmic ray alignment.
> whitespace PR to kick a pipeline build

- ci/build/intermediate-metadata-certificate-request.yaml
The configure-namespace pipeline only builds on changes to ci/build, 
so I've made a change here.
> Add whitespace to kick configure-namespace pipeline

- proxy-node-acceptance-tests/Dockerfile
We currently run all cucumber feature tests in our build pipeline, including tests in features/smoke that should be run only from the Hub smoke pipeline.
In the build pipeline, run only the features/proxy_node.feature, which covers build acceptance tests.
Tested locally with:
`./run-staging-tests.sh`
> 🚭BAU remove smoke tests from build acceptance tests

- ci/build/build-pipeline.yaml
The smoke tests are run separately and should not be part of deployment
Author: @CharlesIC
> BAU: Exclude smoke tests from the build pipeline tests

- chart/templates/_helpers.tpl
- chart/templates/metadata-signing-cert.yaml
- chart/templates/metadata.yaml
- ci/build/test-metadata-certificate-request.yaml
- ci/deploy/integration-metadata-certificate-request.yaml
`test` and `integration` releases should use separate metadata-ca certificates like below:
````
└── verify-root-ca-test-a1
└── proxy-node-metadata-ca-test-a1
├── verify-eidas-proxy-node-metadata-signing-test-a1
└── proxy-node-metadata-ca-integration-a1
└── verify-eidas-proxy-node-metadata-signing-integration-a1
````
> EID-1953 build and integration releases to use separate metadata CA certs

- ci/build/build-pipeline.yaml
- ci/deploy/deploy-pipeline.yaml
The path doesn’t exist and gets ignored but we should remove it from the definition to avoid confusion. Also directory needed to be renamed
> BAU: fixes to integration pipeline

- chart/templates/_helpers.tpl
- ci/build/build-pipeline.yaml
Our deploy namespace `verify-eidas-proxy-node-deploy` needs to be part of our DNS name, which needs to end with `.<namespace>.`london.verify.govsvc.uk.
We have this constraint now so people who are allowed to administer other specific namespaces can't usurp our production system.
Add `.Release.Namespace` to gateway and connector hostnames to accommodate this.
This will affect the `verify-eidas-proxy-node-build` namespace urls too, expect further changes to docs and egress safelists.
We'll create CNAME records under `signin.service.gov.uk` to these urls.
> EID-1894 Include namespace in Proxy Node URLs

- chart/templates/_helpers.tpl
I missed a placeholder in string substitution
> ☺️ EID-1894 Missing string placeholder in connector url

- chart/templates/gateway-ingress-certificate.yaml
- chart/templates/stub-connector-ingress-certificate.yaml
Since we had to add the namespace to the URLs, the default config tried to generate Let's Encrypt certs with the new URLs as the DNS name and by default the CN (Common Name). However, the CN has a limit of 64 chars and the long URLs exceeded that. As as solution, add a DNS name to the list that's short enough to be picked as a CN for the new certs.
This will produce names such as `sc.verify-eidas-proxy-node-deploy.london.verify.govsvc.uk` which are just shy of 60 characters long.
> EID-1964: Add alternative DNS names for the ingress TLS certs that are short enough for CN

- build.gradle
Address a vulnerability indicated in https://snyk.io/vuln/SNYK-JAVA-ORGHIBERNATE-568162
Cannot be applied to `configurations.all` as it results in NoClassDefFoundErrors.
The better solution is to upgrade to Dropwizard 2 which omits the vuln, but this is not a smooth migration.
> BAU Snyk vulnerability in hibernate-validator

- chart/templates/stub-connector-gateway-egress-service-entry.yaml
stub-connector can't read proxy node metadata :(
Allow egress from stub-connector to the gov.uk Proxy Node gateway domain
> EID-1964 ServiceEntry to allow egress from connector to gateway

- docker-compose.yml
- local-startup/vsp/Dockerfile
- startup-docker.sh
We no longer have access to the VSP image built in the pipeline. This change uses the local VSP repo to build the required image.
> BAU: Build VSP image locally for local startup

- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/HubResponseResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/EidasAuthnRequestResourceTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/HubResponseResourceTest.java
In a multi-country Proxy Node, label our metrics by the country entity id, to indicate which countries our Proxy Node traffic is coming from.
Also capture response codes to our gateway urls using `@ResponseMetered`, to help with service level measurements of the Proxy Node.
> EID-1890 Capture request/response metrics per country

- local-startup/docker.env
Make local `docker-compose` work end to end by setting the connector node callback correctly.
You should be able to test an end-to-end journey now by:
1) Starting Hub locally in `ida-hub-acceptance-tests`
2) Building and starting proxy node locally with `./startup-docker.sh --build --local-hub`
3) Starting a journey at http://localhost:6610/
This doesn't allow acceptance tests to run against local dev :(
> Make local docker-compose Proxy Node work end to end

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlParserApplication.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- proxy-node-test/src/main/java/uk/gov/ida/notification/helpers/EidasAuthnRequestBuilder.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/ConnectorNodeCredentialConfiguration.java
Support the following AuthnRequest signing algos within the ESP:
http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha384-rsa-MGF1
http://www.w3.org/2007/05/xmldsig-more#sha512-rsa-MGF1
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512
by using BouncyCastleProvider as a SecurityProvider in the ESP.
Add an integration test to check that signing algo http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1 is supported.
Make http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1 the default signing algo used in stub-connector.
> EID-1949 Accept eIDAS compliant signing algos in ESP

- proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/EidasAssertionBuilder.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/EidasResponseBuilderTest.java
Use constant `SubjectConfirmation.METHOD_BEARER` for the `SubjectConfirmation Method` as the current hard-coded value is incorrect 😞 , thanks @CharlesIC 
Use `get(0)` instead of `iterator.next()` in tests when we want to get the first and only element. This was suggested in a code review and I don't have strong feelings on either option.
> EID-1985 Assertion SubjectConfirmation Method value

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
- proxy-node-acceptance-tests/features/proxy_node.feature
- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/HubResponseResource.java
- proxy-node-gateway/src/main/java/uk/gov/ida/notification/session/GatewaySessionData.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/SamlResponseExceptionMapperResourceRuleTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/TestEidasSamlResource.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/EidasSamlParserProxyTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/TranslatorProxyTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/HubResponseResourceTest.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/session/TestGatewaySessionDataValidator.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/session/TestRedisSessions.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/EidasSamlParserResponse.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/HubResponseTranslatorRequest.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/contracts/verifyserviceprovider/TranslatedHubResponseTestAssertions.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/resources/HubResponseTranslatorResource.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseContainer.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/saml/HubResponseTranslatorTest.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/validations/HubResponseTranslatorRequestValidationTests.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/EidasAuthnRequestContextFactory.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/SendAuthnRequestResource.java
- stub-connector/src/main/resources/uk/gov/ida/notification/stubconnector/views/startpage.mustache
- stub-connector/src/test/java/uk/gov/ida/notification/stubconnector/EidasAuthnRequestContextFactoryTest.java
The PID from the UK IDP is always returned to the country in our eIDAS SAML response, regardless of the name id format requested by the country.
Proxy Node does not publish or respect the transient and unspecified as acceptable name id formats in a SAML Request. Netherlands, for instance, always requests transient ids. Denmark have indicated we are non-compliant due to above.
If a SAML Request indicates a transient name id format, the SAML response to the country will contain a unique random identifier for the PersonIdentifier SAML attribute. In all other cases the PID from the IDP will be returned as the PersonIdentifier SAML attribute. This story will touch three services, the esp, gateway and translator.
- ESP is now able to determine if NameID is transient and stores that in the form …
> EID-1911: NameID format compliance issue

- .snyk
- proxy-node-acceptance-tests/features/proxy_node.feature
- proxy-node-acceptance-tests/features/smoke/integration/ee-request.feature
- proxy-node-acceptance-tests/features/smoke/integration/integration.feature
- proxy-node-acceptance-tests/features/smoke/integration/se-request.feature
- proxy-node-acceptance-tests/features/smoke/production/nl-request.feature
- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
Improve Cucumber tests
- Refactor country specific bits into separate methods for reusability
- Improve spacing and capitalisation to make tests looks clean and tidy
Add smoke tests for Sweden and Estonia
- Move country specific methods to a separate file for better organisation
- Call country methods by constructing their names
> EID-1951: Add integration smoketests for Estonia and Sweden

- proxy-node-acceptance-tests/features/smoke/integration/estonia.feature
- proxy-node-acceptance-tests/features/smoke/integration/integration.feature
- proxy-node-acceptance-tests/features/smoke/integration/sweden.feature
- proxy-node-acceptance-tests/features/smoke/production/netherlands.feature
- proxy-node-acceptance-tests/features/smoke/production/nl-request.feature
To make them consistent with Connector Node tests and enable country status reporting the Proxy Node from alphagov/verify-terraform#1231
- Rename to use country names
See also alphagov/verify-acceptance-tests#93
> Make smoke tests naming consistent with Connector Node smoke tests

- metatron/src/main/java/uk/gov/ida/eidas/metatron/domain/MetadataResolverService.java
- metatron/src/main/java/uk/gov/ida/eidas/metatron/health/CountryMetadataHealthMetrics.java
Set a timeout for the per country client that fetches metadata.
If unset, the client never times out, the metatron never leaves its `init` method, and k8s reads the pod as unhealthy.
The pod is then continually killed and rescheduled.
This has been tested locally with integration config built from `verify-eidas-config` repo.
Also: set the metadata health metrics name to have the conventional `verify-eidas` prefix.
> EID-1973 metatron metadataresolver client timeout

- eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/saml/validation/components/RequestedAttributesValidator.java
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/saml/validation/components/RequestedAttributesValidatorTest.java
According to EU Validator Node team test our Proxy Node is non-compliant. Their assessent:
> Requesting an unsupported mandatory attribute "unknown" along with mandatory attributes (minimum data set for a natural person) leads to authentication failure .According to the EIDAS specification, eIDAS Message Format v1.1-2, section 2.3.2, “Attributes requested that are not supported by an eIDAS-Service MUST be ignored by the eIDAS-Service.”
eIDAS spec states:
> 2.3.2. Requesting Attributes
> 
> ………
> 
> For attributes requested and being mandatory according to the eIDAS minimum data sets and [eIDAS-Attr-Profile] the attribute isRequired of <eidas:RequestedAttribute> MUST be set to “true”. 
> 
> For all optional attributes according to the eIDAS minimum data sets and [eIDAS-Attr-Profile] the …
> ✅ EID-1992 Ignore not required attributes in eIDAS Request

- ci/build/build-pipeline.yaml
This will enable Docker to copy binaries in the following jobs that build images for individual PN apps.
We already do this in the VSP build step but forgot to include this line in the PN build job.
> BAU: Remove .dockerignore when building Proxy Node

- chart/templates/esp-deployment.yaml
- chart/templates/esp-redis-deployment.yaml
- chart/templates/gateway-deployment.yaml
- chart/templates/gateway-redis-deployment.yaml
- chart/templates/metatron-deployment.yaml
- chart/templates/stub-connector-deployment.yaml
- chart/templates/translator-deployment.yaml
- chart/templates/vsp-deployment.yaml
Ensure pod kubeyaml changes each deployment by changing the pod release timestamp.
Pods will then be deleted and rescheduled at deploy time by the deployment controller.
Also remove the `talksToHSM` label from stub-connector, because it doesn't anymore.
We are currently changing the timestamp on the deployment only, which means pods never 'roll'.
We rely on pods being rolled regularly to pick up the latest Metadata and SAML signing certs updated by the [VMC](https://github.com/alphagov/verify-metadata-controller).
We also release growing HSM key handles held by HSM client.
We have a [daily job](https://ci.london.verify.govsvc.uk/teams/eidas-proxy-node-deploy/pipelines/deploy) which will apply these changes.
See zendesk https://govuk.zendesk.com/agent/tickets/4134808 for symptoms.
> timestamp pods during helm templating

- ci/build/build-pipeline.yaml
- proxy-node-acceptance-tests/features/step_definitions/environments.yml
Build pipeline acc tests require a  TEST_ENV env var, and will fallback to local if not present.
Pass in the TEST_ENV env var of build as a key to environment.yaml.
> BAU fix proxy node build acceptance tests

- proxy-node-acceptance-tests/Dockerfile
The proxy-node-acceptance-tests docker image is quite large right now.
This means that concourse does a lot of work copying it around.
This does two things to reduce the image size:
- use the `ruby:2.6.5-slim` image as base, which is smaller
- use multi-stage docker builds so that we don't include build
dependencies (like gcc) in the final artefact
This reduces the size from ~899Mb to ~190Mb.
There was no documentation saying how to test this locally, so I
didn't.
> Reduce the size of the built docker image

- ci/build/build-pipeline.yaml
- ci/deploy/deploy-pipeline.yaml
Ensure that connector node config changes in the `verify-eidas-config` repo are applied only to the correct environment.
i.e. a change in `verify-eidas-config/proxy-node/integration` will trigger an integration deployment, but will not trigger a new build or a production deploy.
Any change in `verify-eidas-config/proxy-node/test` will trigger a new build, and subsequently a deploy to integration and production.
> EID-1960 Apply connector node config to the correct pipeline job

- chart/templates/translator-deployment.yaml
- local-startup/docker.env
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/saml/HubResponseTranslatorTest.java
HubResponseTranslator was using a value derived from the deployment yaml rather than the request.  Now it isn't, it's using Metatron to retrieve that information.
Co-authored-by: Phillip Miller <phillip.miller@digital.cabinet-office.gov.uk>
> EID-1960 Stop using hardcoded values

- chart/templates/esp-deployment.yaml
- local-startup/docker.env
The ESP no longer refers to a singe connector node, so remove this left-over config.
Tested with local docker.
> EID-1960 Clean up ESP config

- ci/build/build-pipeline.yaml
the name for the test image is wrong.
> Fix test image name

- proxy-node-translator/src/dist/config.yml
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/configuration/TranslatorConfiguration.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/EidasFailureResponseGenerator.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/EidasResponseGenerator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/base/TranslatorAppRuleTestBase.java
Delete proxyNodeMetadataForConnectorNodeUrl from the Configuration class and from the yaml file too.
As this is no longer an env var for k8s the value is never interpolated and Java tries to parse ${PROXY_NODE_METADATA_FOR_CONNECTOR_NODE_URL} as a URL.  Unsurprisingly this doesn't end well and the translator doesn't start at all which means tests never get run.
> EID-1960 Remember to delete the config value

- cloudhsm/Dockerfile
Follow instructions at https://docs.aws.amazon.com/cloudhsm/latest/userguide/install-and-configure-client-linux.html for Amazon Linux 2.
Cherry pick this onto the `release/single-country-legacy` branch once it passes the build.
> BAU upgrade CloudHSM client to latest version

- metatron/src/main/java/uk/gov/ida/eidas/metatron/domain/MetadataResolverService.java
The MetadataResolverService needs to create a MetadataResolver for each configured country.  When it does this in series then any faulty countries must time out before the next country can be resolved.  As the resolvers are created during a stream operation we can replace `stream()` with `parallelStream()`.
Using the integration configuration, it can reduce the time taken to create the resolvers from ~42s to ~12s. Of the 12s, at least 10 are the time it takes for countries to timeout.  Reducing the timeout numbers in `getClient()` further speeds up the startup to ~8s.
You can test it by:
* generating a `countriesConfig.yaml` by running `verify-eidas-config.git/tools ./gradlew run --args="generate-config --environment=integration"`
* setting the environment variables `CONFIG_FILE` and …
> BAU Use parallelStream in MetadataResolverService constructor

- chart/templates/gateway-ingress-gateway.yaml
- chart/values.yaml
- ci/deploy/deploy-pipeline.yaml
add `qwac.enabled: false` to `values.yaml` so that the default is to not use QWAC
add conditional sections to `gateway-ingress-gateway.yaml` under the `tls` and `hosts` sections so that when `qwac.enabled` is true, `tls` is handled differently and a different hostname is used.
add `--set "gateway.qwac=true"` to inline bash used in `render-manifests` in `prod/depoly-pipeline.yaml` so that production uses the QWAC
cross fingers and hope for the best.
> EID-1919 Configure Gateway to use QWAC

- chart/templates/_helpers.tpl
Production doesn't include the environment in the hostname.
> Fix GOV.UK Gateway hostname in production

- .snyk
- metatron/build.gradle
- metatron/src/test/java/uk/gov/ida/eidas/metatron/apprule/MetatronAppRuleTests.java
- proxy-node-test/src/main/java/uk/gov/ida/notification/apprule/rules/AppRule.java
Add test for `metatron` ingress and egress logging including verifying logging of `PROXY_NODE_JOURNEY_ID` on ingress.
Modify AppRule to enable injection of `ProxyNodeJsonClient` when making a `GET` request (since `ProxyNodeJsonClient` passes the headers to `metatron` that need logging).
Modify `build.gradle` so that `ida_utils` dependencies are available to `testImplementation`.
> BAU Test Metatron ingress/egress logging

- chart/templates/gateway-ingress-gateway.yaml
From the eIDAS spec: 
> eIDAS nodes MUST use TLS 1.2. Prior TLS versions MUST NOT be accepted.
Improve TLS security. The list of (old) browsers that could not use TLS1.2 is: https://caniuse.com/#feat=tls1-2
> EID-1919 eIDAS requirement: TLS v1.2 must be used

- ci/deploy/multi-country-killswitch-pipeline.yaml
This image is now continuously deployed, we should prefer it.  We're
moving away from the `gdsre` organisation to the `govsvc` one.
> uSe new govsvc/aws-ruby image

- cloudhsm/jdk-jce-image/Dockerfile
- proxy-node-translator/build.gradle
The build is broken as we're referencing libs which are not part of the latest CloudHSM JCE release.
We use the `latest` CLoudHSM JCE release, which contains these jars:
cloudhsm-3.1.2.jar
cloudhsm-test-3.1.2.jar
hamcrest-all-1.3.jar
junit.jar
log4j-api-2.13.3.jar
log4j-core-2.13.3.jar
Remove the hamcrest, cloudhsm-test and junit jars, and accept others as dependencies for this API.
> BAU Use latest provided CloudHSM JCE dependencies

- ci/deploy/deploy-pipeline.yaml
- ci/deploy/killswitch-pipeline.yaml
Check the `lock-production` S3 bucket to see if someone has set a "lock" on the prod deploy pipeline.
Slack when the pipeline is locked, and the deploy won't happen.
Also remove the `force unlock` job which was a carry-over from the Hub pipeline as isn't used here.
> 🛑 EID-1994 Stop Proxy Node Prod deploy if pipeline locked via S3

- ci/deploy/deploy-pipeline.yaml
The [deploy-to-production job is currently failing](https://ci.london.verify.govsvc.uk/teams/eidas-proxy-node-deploy/pipelines/deploy/jobs/deploy-production/builds/58).
Evaluate the check-lockfile task ruby script as utf-8, to allow emojis.
I tested this on a local concourse with the ruby code below and it works with `# encoding: utf-8`, fails with a `-e:4: invalid multibyte char (US-ASCII)` message without the encoding line.
````
run:
path: ruby
args:
- -e
- |
require 'json'
contents = {
"is_locked" => true
}
File.open("1.lock","w") do |f|
f.write(contents.to_json)
end
most_recent_lockfile = JSON.parse(File.read(Dir.glob('*.lock').sort.reverse.first))
if most_recent_lockfile["is_locked"] == true
puts '🛑 Production Deploy Pipeline is locked.'
exit 1
else
puts '👍 Production Deploy Pipeline …
```
> EID-1994 Evaluate ruby script as UTF-8 (Emojis FTW)

- proxy-node-translator/build.gradle
Reverts a commit that attempts to not use specific cloudhsm JCE jars.
Use the latest JCE client libs made available from building `cloudhsm/jdk-jce-image/Dockerfile`.
This is a bit of a hack until we can find a way to accept the latest JCE jars from AWS CloudHSM in a non-hardcoded way.
> EID-2001 include specific libs bundled with latest CloudHSM JCE client

- ci/deploy/killswitch-pipeline.yaml
Delete deployments and virtualservices from production only, by targeting the label `app.kubernetes.io/instance=production`.
Previously we deleted integration resources too, as they're on the same namespace.
> 🤭 EID-1944 Kill only production resources

- .snyk
- ci/deploy/deploy-pipeline.yaml
Override the prod default error page [set in values.yaml](https://github.com/alphagov/verify-proxy-node/blob/0530d32c4327cfc1786b7b3543f0907d696a6c98/chart/values.yaml#L50). It's set to an integration url by default.
Also ignore a snyk vuln that is not used directly at runtime, for another month. We need to upgrade to Dropwizard 2 to mitigate.
> BAU set prod error page url for Proxy Node

- chart/templates/translator-deployment.yaml
- eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java
- proxy-node-acceptance-tests/features/acceptance/proxy_node.feature
- proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HubResponseAppRuleTests.java
- proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/HubResponseResourceTest.java
- proxy-node-shared/src/main/java/uk/gov/ida/notification/contracts/HubResponseTranslatorRequest.java
- proxy-node-shared/src/test/java/uk/gov/ida/notification/contracts/verifyserviceprovider/TranslatedHubResponseTestAssertions.java
- proxy-node-test/src/main/java/uk/gov/ida/notification/apprule/rules/TestMetadataResource.java
- proxy-node-test/src/main/java/uk/gov/ida/notification/apprule/rules/TestMetatronResource.java
- proxy-node-translator/src/dist/config.yml
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/configuration/TranslatorConfiguration.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/EidasResponseGenerator.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseContainer.java
- proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/base/TranslatorAppRuleTestBase.java
- proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/saml/HubResponseTranslatorTest.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/exceptions/mappers/TemplatedResponseWebApplicationExceptionMapper.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/ReceiveResponseResource.java
- stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/views/ResponseView.java
- stub-connector/src/main/resources/uk/gov/ida/notification/stubconnector/views/response.mustache
Set an `issuerId` field in `HubResponseTranslator`. Use this `issuerId` field to be the SAML `Issuer` of the response.
We're presently incorrectly setting the `Issuer` to be the country entity id.
The value of `issuerId` is helm templated into the translator deployment with `{{ include "gateway.entityID" . }}`
Unit, integration (apprule) and acceptance tests have been updated.
> EID-2012 set eIDAS response issuer as Proxy Node entity id

- proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/metadata/MetadataTest.java
- proxy-node-test/src/main/resources/expired_connector_node_metadata_template.xml
Unit tests are failing as its past the expiry date on the test metadata template `connector_node_metadata_template.xml`.
Update this expiry date to the future, and introduce a new test that asserts expired metadata entity descriptor should make that metadata invalid.
> BAU Test for expired metadata entity descriptor

- ci/integration/deploy-pipeline.yaml
- ci/prod/deploy-pipeline.yaml
Create one-off pipeline jobs to `kapp delete` deployments we don't need anymore. Note this is on the `release/single-country-legacy` branch.
This follows the merged [PR to remove the jobs to deploy these apps](https://github.com/alphagov/verify-proxy-node/pull/647).
I'm assuming the `kubectl config` that is set up in the task is required by `kapp`.
> EID-2019 remove legacy proxy node deployments

- .snyk
- ci/deploy/production-dashboard.yaml
A dashboard for the new Prod Proxy Node containing:
* num of successful responses to connectors over $TimePeriod
* the current held HSM sessions, 
* request / response rate over $TimePeriod
* ratio of requests to Proxy Node that we process successfully
* ratio of responses to Proxy Node that we process successfully
It was authored in Grafana to look like this:
> BAU New Proxy Node Dashboard

- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
Netherlands are now connected to our multi-country proxy node.
Updated the URL and followed the steps that are documented in the document they sent us.
This feature can be tested locally by:
- updating the `run-tests.sh` on line 80 to point at `features/smoke/production`
- and then run the `run-tests.sh` script (use the `run-tests.sh -c` to run using chrome, this avoids selenium errors for me)
https://govukverify.atlassian.net/browse/EID-2020
> EID-2020: Update Netherlands proxy node smoke test

- proxy-node-acceptance-tests/features/smoke/production/spain.feature
- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
Add the Capybara smoke test with feature spain.feature.
The smoke test will be run by the hub smoke test pipeline.
This feature can be tested locally by:
- updating the `run-tests.sh` on line 80 to point at `features/smoke/production`
- and then run the `run-tests.sh` script  (use the `run-tests.sh -c` to run using chrome, this avoids selenium errors for me)
Subsequent PR in `verify-terraform`: https://github.com/alphagov/verify-terraform/pull/1335
https://govukverify.atlassian.net/browse/EID-2020
> EID-2020: Spain proxy node smoke test

- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
Although running locally with'-c' flag  works fine, concourse is complaining:
`Element <a href="#"> is not clickable at point (537.75,377.75) because another element <span> obscures it`
So running without the '-c' flag gives the same error locally as what is seen on concourse. This change has fixed this error locally, but the final step seems to fail.
But the last step seems to pass in all the tests on concourse so we can assume that it will work.
> EID-2020: Fix Netherlands smoke test

- proxy-node-acceptance-tests/features/smoke/production/sweden.feature
- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
Currently Sweden has an integration smoke test which use the same steps.
Named the first step 'SwedenProduction' as that is the easiest way to determine them apart.
It uses the same steps following that as the integration journey, it just uses a different url.
This feature can be tested locally by:
- updating the `run-tests.sh` on line 80 to point at `features/smoke/production`
- and then run the `run-tests.sh` script 
Subsequent PR in `verify-terraform`: https://github.com/alphagov/verify-terraform/pull/1340
https://govukverify.atlassian.net/browse/EID-2020
> EID-2020: Sweden prod proxy node smoke

- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
Currently the smoke test is being flakey.
The `click_link` is what ive discovered to cause the issues.
Netherlands anchor tag is set up like this `href="#"`
So being more specific looking for the tag to click on might solve this.
https://github.com/teamcapybara/capybara/issues/379 <-- using a solution from this thread
> EID-2020: Attempt #2 fix Netherlands smoke test

- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
Ever so slightly different syntax to click a button. If this does not work then I will be out of ideas. 
The cause of the issue is definitely regarding this line. I have found the html that the error mentions in the page source but coming up with a solution is proving difficult as all tests past fine locally and the error cant be reproduced. 
Fingers crossed this works     
> EID-2020: Attempt 3 to fix Netherlands smoke

- proxy-node-acceptance-tests/features/smoke/production/italy.feature
- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
Add the Capybara smoke test with feature italy.feature.
The smoke test will be run by the hub smoke test pipeline.
This feature can be tested locally by:
- updating the `run-tests.sh` on line 80 to point at `features/smoke/production`
- and then run the `run-tests.sh` script
Subsequent PR in `verify-terraform`: https://github.com/alphagov/verify-terraform/pull/1346
https://govukverify.atlassian.net/browse/EID-2020
> EID-2020: Italy proxy node smoketest

- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
We are executing a javascript to click button. This should stop the error of element obscuring the link
> EID-2020: Fix netherlands smoketest

- proxy-node-acceptance-tests/features/step_definitions/country_journeys.rb
The Italian proxy node test is _very_ flaky. We often see the test
failing at the Italians connector-node. There are a series of pages
which are auto-submitted with JS. One particular page's JS is fired by a
`load` event on the window. There may be a race condition as a lot of
the time this doesn't happen with Selenium and the journey stalls.
This adds a conditional check to see if we've stalled. If so, we
manually call the JS required to submit the page.
> BAU: Fix Italian proxy node test

- .snyk
- ci/deploy/integration-lock.yaml
- ci/deploy/killswitch-pipeline.yaml
A way to remove the deployment of the Integration Proxy Node, via a concourse pipeline.
We already have a kill switch for production, but not integration. This will give us the confidence that the kill switch mechanics work, but won't affect production. We need more confidence as we may have to switch off the Proxy Node at a very specific out-of-hours time.
The change is mostly a copy-paste of the prod jobs, plus a new S3Bucket type to hold the integration lockfile.
> EID-2081 Proxy Node  integration kill switch
