alphagov/verify-proxy-node

Brewfile, README.md
My first pull request, be kind ;) Helps team members run minikube cluster locally.
=> Updated README and Brewfile to reflect latest understanding of how to run minikube locally

build.gradle, eidas-saml-parser/build.gradle, eidas-saml-parser/src/dist/config.yml, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlConfiguration.java, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/RequestDto.java, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/ResponseDto.java, eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java, settings.gradle
Created a new Dropwizard application for the eIDAS SAML Parser service.
I've created a single resource `EidasSamlResource` that will be
responsible for processing the eIDAS AuthnRequest.
=> EID-1286/1295: Create eidas-saml-parser project

eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java
* Fixes broken build, what with all the PRs coming in
=> BAU: fix broken build

docker-compose.yml, eidas-saml-parser/src/dist/config.yml
- Add dockerFile for esp and add to docker-compose
- Change port so it isn't using the same as the gateway
=> Bau - Add Dockerfile for ESP

docker-compose.yml, eidas-saml-parser/build.gradle, proxy-node-chart/charts/eidas-saml-parser/.helmignore, proxy-node-chart/charts/eidas-saml-parser/Chart.yaml, proxy-node-chart/charts/eidas-saml-parser/templates/parser-deployment.yaml, proxy-node-chart/charts/eidas-saml-parser/templates/parser-service.yaml, proxy-node-chart/charts/eidas-saml-parser/values.yaml, proxy-node-chart/charts/proxy-node-gateway/templates/gateway-deployment.yaml, proxy-node-chart/values.yaml, proxy-node-translator/build.gradle
This adds the config to get the ESP running in k8's
=> EID-1332: Adding Helm Charts for ESP.

stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/MetadataResource.java
Update the protocol supported for the SPSSODescriptor.
=> EID 1312: Stub Connector Metadata Protocol fix.

eidas-saml-parser/src/dist/config.yml, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java, pki/Gemfile.lock, proxy-node-chart/charts/eidas-saml-parser/templates/parser-deployment.yaml, proxy-node-chart/charts/eidas-saml-parser/templates/parser-service.yaml, proxy-node-gateway/Dockerfile, stub-connector/Dockerfile
Added the service health check to the ESP,
Deleted some docker files that weren't used.
Updated Charts to make it work with kubeneties.
=> EID-1335: Fix the health checks for ESP

proxy-node-gateway/src/main/java/uk/gov/ida/notification/configuration/TranslatorServiceConfiguration.java, proxy-node-translator/src/dist/config.yml, proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java, proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/configuration/TranslatorConfiguration.java, proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java, proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/base/TranslatorAppRuleTestBase.java, proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/rules/TranslatorAppRule.java
Removed unused code after the restructure
=> EID-1287: Translator cleanup

.gitignore, pki/generate, proxy-node-chart/charts/verify-service-provider/.helmignore, proxy-node-chart/charts/verify-service-provider/Chart.yaml, proxy-node-chart/charts/verify-service-provider/templates/_helpers.tpl, proxy-node-chart/charts/verify-service-provider/templates/config.yaml, proxy-node-chart/charts/verify-service-provider/templates/deployment.yaml, proxy-node-chart/charts/verify-service-provider/templates/service.yaml, proxy-node-chart/charts/verify-service-provider/values.yaml, startup.sh
Add the chart for the Verify Service Provider to the proxy node.
=> Add vsp chart

.gitignore, proxy-node-chart/charts/metadata-controller/.helmignore, proxy-node-chart/charts/metadata-controller/Chart.yaml, proxy-node-chart/charts/metadata-controller/templates/_helpers.tpl, proxy-node-chart/charts/metadata-controller/templates/customer-ca-crt-configmap.yaml, proxy-node-chart/charts/metadata-controller/templates/metadata-crd.yaml, proxy-node-chart/charts/metadata-controller/templates/role-binding.yaml, proxy-node-chart/charts/metadata-controller/templates/role.yaml, proxy-node-chart/charts/metadata-controller/templates/serviceaccount.yaml, proxy-node-chart/charts/metadata-controller/templates/statefulset.yaml, proxy-node-chart/charts/metadata-controller/values.yaml
A chart for the metadata controller.
Solo: @blairboy362
=> Add the metadata controller chart.

build.gradle, eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/EidasSamlResourceTest.java, eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java, eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/base/EidasSamlParserAppRuleTestBase.java, eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/saml/EidasAuthnRequestValidatorTest.java, gradle/wrapper/gradle-wrapper.properties, proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/EidasAuthnRequestAppRuleTests.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HubResponseAppRuleTests.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/EidasSamlParserProxyTest.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/TranslatorProxyTest.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/EidasAuthnRequestResourceTest.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/HubResponseResourceTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/SamlFormViewBuilderTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/contracts/verifyserviceprovider/TranslatedHubResponseTestAssertions.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/ResponseAssertionDecrypterTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/ResponseAssertionEncrypterTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/SamlObjectMarshallerTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/SamlObjectSignerTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/SamlParserTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/metadata/MetadataTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/validation/HubResponseValidatorTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/validation/components/RequestIdWatcherTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/proxy/VspProxyGenerateRequestTest.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/proxy/VspProxyTranslateResponseTest.java, proxy-node-test/src/main/java/uk/gov/ida/notification/helpers/HtmlHelpers.java, proxy-node-translator/src/test/java/uk/gov/ida/notification/translator/apprule/HubResponseTranslatorAppRuleTests.java, stub-connector/src/test/java/uk/gov/ida/notification/apprule/EidasResponseValidatorAppRuleTests.java
Migrated away from Junit and moved all tests to AssertJ
Updated the libraries aswell while i was at it.
=> EID-1353, Switch JUnit to be AssertJ instead.

proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/session/storage/InMemoryStorage.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/session/storage/RedisStorage.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/session/storage/SessionStore.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/resources/EidasAuthnRequestResourceTest.java
If a session already exists override the session object when a new journey is run.
=> Now destroys old session object if reused

proxy-node-gateway/src/main/java/uk/gov/ida/notification/session/GatewaySessionData.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/EidasAuthnRequestAppRuleTests.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/HealthCheckAppRuleTests.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/apprule/rules/GatewayAppRule.java
Edited the session object to be serialised back from JSON,
Some other tidy ups along the way.
=> BAU: Fixed redis serialisation problem

proxy-node-acceptance-tests/Dockerfile, proxy-node-acceptance-tests/Gemfile.lock, proxy-node-acceptance-tests/docker-compose.yml, proxy-node-acceptance-tests/features/proxy_node.feature, proxy-node-acceptance-tests/features/step_definitions/user_steps.rb, proxy-node-acceptance-tests/features/support/env.rb, proxy-node-acceptance-tests/run-staging-tests.sh, proxy-node-acceptance-tests/run-tests-with-docker.sh, stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/SendAuthnRequestResource.java
Theses tests should check if the proxy node is running.
=> Updated acceptance tests for staging

eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/EspAuthnRequestAppRuleTest.java, proxy-node-acceptance-tests/features/proxy_node.feature, proxy-node-acceptance-tests/features/step_definitions/user_steps.rb, proxy-node-acceptance-tests/run-staging-tests.sh, proxy-node-acceptance-tests/run-tests-with-docker.sh, proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/validation/components/LoaValidator.java, stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/SendAuthnRequestResource.java, stub-connector/src/main/resources/uk/gov/ida/notification/stubconnector/views/startpage.mustache, stub-connector/src/test/java/uk/gov/ida/notification/apprule/base/StubConnectorAppRuleTestBase.java
Modified stub connector to create the new requests.
Added some acceptance tests
Fixed ESP validator to accept LOA Low
=> EID-1349, Tests for loa low & high.

build.gradle, proxy-node-translator/build.gradle
- SE softhsm libraries still being included even though no longer used.
=> EID: Remove softhsm references in Gradle Scripts

eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java, eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/IstioHeaderTest.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/IstioHeaderMapperFilter.java
Changes needed to support RE, http tracing solution
=> EID-1385: Added filter to pass on istio headers

proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
- Accidentally committed change
=> Bau - Remove modifier

eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java, eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/IstioHeaderTest.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/GatewayApplication.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/IstioHeaderMapperFilter.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/IstioHeaders.java, proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java, stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/StubConnectorApplication.java
This is adding the Istio header filter to all of the applications to carry the headers from a incoming request to a out going response.
This PR is 95% tests
=> EID-1387: Added filter to pass through istio headers

proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/ProxyNodeLogger.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/ProxyNodeLoggerTest.java
The test is our best attempt under the circumstances.
=> Log correct stack frame depth

eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlResource.java, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/saml/validation/components/AssertionConsumerServiceValidator.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/BaseExceptionToErrorPageMapper.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/ExceptionToSamlErrorResponseMapper.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/EidasAuthnRequestResource.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/configuration/CloudHsmCredentialConfiguration.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/configuration/KeyFileCredentialConfiguration.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/ResponseAssertionDecrypter.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/saml/SamlObjectSigner.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/ProxyNodeLogger.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/ProxyNodeLoggerTest.java, proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/resources/HubResponseTranslatorResource.java, stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/resources/ReceiveResponseResource.java
Change half the changes Karol made ten minutes ago.
=> EID-1486 Make ProxyNodeLoggerStatic

proxy-node-gateway/src/main/java/uk/gov/ida/notification/configuration/EidasSamlParserServiceConfiguration.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/configuration/TranslatorServiceConfiguration.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/proxy/EidasSamlParserProxy.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/proxy/TranslatorProxy.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/EidasSamlParserProxyTest.java, proxy-node-gateway/src/test/java/uk/gov/ida/notification/proxy/TranslatorProxyTest.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/proxy/ProxyNodeJsonClient.java
Provide a JsonClient for the ProxyNode which inserts a JourneyId into headers by default.
=> EID-1497 ProxyNode JsonClient to insert JourneyId into headers

chart/templates/_helpers.tpl, chart/templates/esp-deployment.yaml, chart/templates/stub-connector-metadata-network-policy.yaml, chart/templates/stub-connector-metadata.yaml, chart/values.yaml
We're getting ready to connect first country in integration ... there were a few stub-connector specific bits of config still in the chart that we need to clean up first...
=> Few chart tweaks for connecting a country in integration

chart/templates/saml-metadata.yaml
Update metadata contact details to something more meaningful prior to integration with Netherlands
=> Update Proxy Node Metadata contact details

Dockerfile
After recent changes to `build.gradle`
=> BAU: Fix Docker build

chart/templates/stub-connector-deployment.yaml, chart/templates/translator-deployment.yaml
Update issuer in SAML response
=> Update response issuer to be entityID in metadata spec

ci/build/release-pipeline.yaml
=> Reference the correct input

chart/templates/connector-metadata-egress-destination-rules.yaml, chart/templates/connector-metadata-egress-virtual-service.yaml, chart/templates/hub-egress-destination-rules.yaml
Before merging:
Merge with: https://github.com/alphagov/gsp/pull/279
=> Migrate egress safelist to mTLS

ci/build/build-pipeline.yaml
..using a job from the new pipeline :hocho:
feel free to revert this once the old pipeline is gone
=> delete old release pipeline

ci/build/build-pipeline.yaml
this job has done it's work.  it can be deleted now
=> remove unneeded job

ci/sandbox/build-pipeline.yaml
=> BAU: Add build pipeline to Sandbox cluster

ci/sandbox/build-pipeline.yaml
=> BAU: Add build pipeline to Sandbox

ci/prod/killswitch-pipeline.yaml, ci/sandbox/killswitch-pipeline.yaml
⚠️ ⚠️ ⚠️ This creates a pipeline that can nuke the proxynode. ⚠️ ⚠️ ⚠️
=> EID-1682: Add in pipeline to murder the proxy node on que

proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseTranslator.java
Applied reformatting to a file
=> Whitespace-only commit to restart the pipeline

proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/BaseExceptionToErrorPageMapper.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/exceptions/mappers/ExceptionToSamlErrorResponseMapper.java, proxy-node-gateway/src/main/java/uk/gov/ida/notification/resources/HubResponseResource.java
Moar counters
https://govukverify.atlassian.net/browse/EID-1775
=> EID-1775 add counters for two error handling scenarios

ci/build/build-pipeline.yaml
Remove directive separator, in reality to push a new PR through pipeline
=> EID-1822 whitespace PR

ci/build/build-pipeline.yaml, ci/integration/deploy-pipeline.yaml, ci/prod/deploy-pipeline.yaml, ci/prod/killswitch-pipeline.yaml, ci/sandbox/build-pipeline.yaml, ci/sandbox/deploy-pipeline.yaml, ci/sandbox/killswitch-pipeline.yaml
Cherry pick of #374 from master.
=> Bau cherry pick of remove commit verification keys

.travis.yml, ci/build/build-pipeline.yaml
A cherry-pick of master PR https://github.com/alphagov/verify-proxy-node/pull/395 onto the **release** branch.
=> EID-1822 🍒cherry-pick: add commit short ref to git-release

ci/prod/dashboard.yaml
Monitor open sessions so as to keep an eye on resource leaks
https://govukverify.atlassian.net/browse/EID-1875
=> EID-1875 HSM monitoring on the eIDAS dashboard

.snyk, chart/templates/esp-deployment.yaml, chart/templates/esp-redis-deployment.yaml, chart/templates/gateway-deployment.yaml, chart/templates/gateway-redis-deployment.yaml, chart/templates/stub-connector-deployment.yaml, chart/templates/translator-deployment.yaml, chart/templates/vsp-deployment.yaml, ci/build/build-pipeline.yaml
This is a cherry pick from [a release branch PR](https://github.com/alphagov/verify-proxy-node/pull/419).
The [delete job for that pipeline](https://ci.london.verify.govsvc.uk/teams/proxy-node-build/pipelines/build-release) works 👍
=> 🍒EID-1872 Delete test release daily and before testing

ci/prod/dashboard.yaml
- only obvious change is removal of threshold/alert
=> EID-1875 attempt to fix eIDAS dashboard

ci/prod/dashboard.yaml
Adding back the threshold that we removed when we were fixing the syntax.
- also fix size of other panel
(OMG the order and indentation has changed _again_)
=> EID-1875 add back threshold so we can see if HSM sessions go too high

.snyk, ci/build/build-pipeline.yaml, ci/integration/deploy-pipeline.yaml, ci/prod/deploy-pipeline.yaml, ci/prod/killswitch-pipeline.yaml, ci/sandbox/build-pipeline.yaml, ci/sandbox/deploy-pipeline.yaml, ci/sandbox/killswitch-pipeline.yaml
See https://github.com/alphagov/gsp/pull/858
=> Replace concourse.k8s.io API group with concourse.govsvc.uk

ci/build/test-pki.yaml, ci/integration/killswitch-pipeline.yaml, ci/integration/smoke-test.yaml, ci/integration/test-pki.yaml, ci/sandbox/test-pki.yaml
Should've put this in https://github.com/alphagov/verify-proxy-node/pull/438
=> Replace some more concourse.k8s.io API group references that I missed

ci/build/build-pipeline.yaml, ci/sandbox/build-pipeline.yaml
We've spent enough time trying to make this hack work in the new world.
Make it a bit less hacky.
=> Replace alpine-image hackery

ci/sandbox/test-pki.yaml
Follows-up https://github.com/alphagov/verify-proxy-node/pull/435 and https://github.com/alphagov/verify-proxy-node/pull/444
See https://github.com/alphagov/gsp/pull/858
=> Fix Pipeline apiVersion

ci/sandbox/build-pipeline.yaml
=> More fixes to sandbox build pipeline

ci/build/build-pipeline.yaml, ci/build/image-repositories.yaml, ci/build/principal.yaml, ci/sandbox/build-pipeline.yaml, ci/sandbox/image-repositories.yaml, ci/sandbox/principal.yaml
Cherry-picks #455, #460, #461, #462, #463, #464, #465, #466, #467, #468, #469, and #470 to release/single-country-legacy, with the main difference being the removal of metatron.
=> Replace Harbor with GSP ImageRepositories

chart/templates/gateway-ingress-virtual-service.yaml, chart/templates/stub-connector-gateway-egress-service-entry.yaml, chart/templates/stub-connector-ingress-virtual-service.yaml
Pre-requisite of the dev-namespaces work.
=> Isolate istio resources to current namespace only.

ci/integration/deploy-pipeline.yaml, proxy-node-vsp-config/verify-service-provider.yml
This deployment uses the "custom Hub" configuration for the VSP and has the Stub Connector enabled
=> BAU: Deploy Proxy Node instance to connect to the HMRC IDP

ci/integration/deploy-pipeline.yaml
Whitespace commit to kick pipeline
=> BAU: Kick pipeline

ci/integration/deploy-pipeline.yaml
Resigned commits so the pipeline would stop complaining
=> BAU: Resign commits

eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/base/EidasSamlParserAppRuleTestBase.java
Some time ago, builds stopped building.  The test that fails doesn't fail locally or when Travis runs it.  This suggests some kind of race is going on and the wrong thing wins in the pipeline.  It looks like it's the mockatron that's providing the null pointer exceptions when it should be providing port numbers so ~I've changed the order in which~ make the test wait for the port to become available before the RuleChain is executed to see if that helps.
=> BAU Un-break the broken build

chart/templates/vsp-deployment.yaml, chart/values.yaml, ci/integration/deploy-pipeline.yaml
Pipe the VSP config environment variables from deployment pipeline to the pod
=> BAU: Add plumbing to set VSP config env vars

build.gradle
https://snyk.io/vuln/SNYK-JAVA-IODROPWIZARD-552147
=> BAU: Upgrade dropwizard due to vulnerability found by snyk

eidas-saml-parser/build.gradle, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlApplication.java, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlParserApplication.java, eidas-saml-parser/src/main/java/uk/gov/ida/notification/eidassaml/EidasSamlParserConfiguration.java, eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/base/EidasSamlParserAppRuleTestBase.java, eidas-saml-parser/src/test/java/uk/gov/ida/notification/eidassaml/apprule/rules/EidasSamlParserAppRule.java, proxy-node-shared/src/main/java/uk/gov/ida/notification/shared/proxy/MetatronProxy.java, proxy-node-shared/src/test/java/uk/gov/ida/notification/shared/proxy/MetatronProxyTest.java, proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/TranslatorApplication.java, proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/configuration/TranslatorConfiguration.java, proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/EidasResponseGenerator.java, proxy-node-translator/src/main/java/uk/gov/ida/notification/translator/saml/HubResponseContainer.java
Change DTOs between Gateway and the Translator to not pass information that can be obtained from the new Metadata Service.
=> EID-1838: Clean up dtos between gateway and translator

.snyk, build.gradle, proxy-node-acceptance-tests/features/step_definitions/user_steps.rb
Copy has changed on the Sign in with GOV.UK Verify page.
Update test to assert this new copy.
Cherry from https://github.com/alphagov/verify-proxy-node/pull/528
=> 🍒BAU Update Proxy Node acceptance tests

.travis.yml, build.gradle, ci/deploy/test-pki.yaml
This is step 1 to update CI pipeline to deploy Proxy Node to Integration
Copied test-pki from the build pipeline and renamed to deploy 
Story: https://govukverify.atlassian.net/secure/RapidBoard.jspa?rapidView=144&projectKey=HUB&modal=detail&selectedIssue=EID-1894
Also cherry pick over `Upgrade commons-codec` to help fix a snyk found vulnerability
=> EID-1894: Add test-pki to the deploy pipeline

ci/deploy/deploy-integration-pipeline.yaml
**--- NOT TO MERGE YET ---**
Copied deploy.yaml from ci/integration and modify to have only one integration release
=> EID-1894: Add the deploy.piepline.yaml

ci/deploy/deploy-pipeline.yaml
* Create the integration country k8s `configmap` that `metatron` requires.
* A merge to `verify-eidas-config` `integration` directory will result in an integration release.
* Renamed pipeline file to `deploy-pipeline.yaml` as it will deploy to prod also
=> 🗺EID-1894 Create Integration configmap for deploy

ci/deploy/deploy-pipeline.yaml
[The deploy pipeline said no to our yaml](https://ci.london.verify.govsvc.uk/teams/eidas-proxy-node-deploy/pipelines/configure-namespace/jobs/apply/builds/11), this indents it correctly 🤞
=> EID-1960 Fix identation of prod release yaml

metatron/src/main/java/uk/gov/ida/eidas/metatron/MetatronApplication.java
`MetatronResource` was annotated with `@IngressEgressLogging` but the appropriate filters were not registered so nothing gets logged.  I'll admit, I'm not entirely sure what will be recorded when the logging does commence as Metatron is pretty lightweight in terms of it's calls so I'm not sure what information will be available to log.
=> BAU Add logging filters to Metatron

ci/deploy/multi-country-killswitch-pipeline.yaml
Don't think we need mastertinner/build-metadata-resource as its never ultimately used
Fly validated and set this pipeline locally and seems to be ok
=> Kill switch suggestion for WIP killswitch

ci/deploy/multi-country-killswitch-pipeline.yaml, ci/deploy/verify-2nd-line-slack-webhook.yaml
I don't really expect this to work but it might just have the parts it needs to do what we want it to.
Ideally we'd be able to see the lock file writing happen (lock/unlock) and then see if that happens when the killswitch is triggered.  Then we could add in a check for the lockfile to the deploy stuff.
=> EID-1994 Killswitch

ci/deploy/killswitch-pipeline.yaml
I accidentally deleted previously 😣
=> 🤫EID-1994 Add slack resource type

metatron/src/main/java/uk/gov/ida/eidas/metatron/MetatronApplication.java, metatron/src/main/java/uk/gov/ida/eidas/metatron/MetatronConfiguration.java
Provide a url for Prometheus to scrape metrics 🤦 
This configuration is present in our other services.
=> BAU Add PrometheusBundle to Metatron

stub-connector/src/main/java/uk/gov/ida/notification/stubconnector/views/ResponseView.java
Add missing getter for issuerId, in order to surface the issuer in stub-connector response page
=> EID-2012 Add getter for issuer

.snyk, build.gradle, gradle/wrapper/gradle-wrapper.properties, proxy-node-shared/src/test/java/uk/gov/ida/notification/saml/metadata/MetadataTest.java, proxy-node-test/src/main/resources/expired_connector_node_metadata_template.xml, snyk/configurations.sh
Series of commits to get the build green on this legacy single-country Proxy Node branch.
This is to prepare for a Netherlands truststore update we have to do 12th Oct
=> Update build config in Proxy Node release branch

ci/integration/deploy-pipeline.yaml, ci/prod/deploy-pipeline.yaml
kapp delete on concourse is blocked on a y/n prompt. Answer yes.
=> EID-2019 answer yes on kapp delete

chart/templates/esp-deployment.yaml, chart/templates/esp-redis-deployment.yaml, chart/templates/gateway-deployment.yaml, chart/templates/gateway-redis-deployment.yaml, chart/templates/stub-connector-deployment.yaml, chart/templates/translator-deployment.yaml, chart/templates/vsp-deployment.yaml, ci/build/build-pipeline.yaml, ci/build/test-pki.yaml, ci/integration/deploy-pipeline.yaml, ci/integration/killswitch-pipeline.yaml, ci/integration/test-pki.yaml, ci/prod/deploy-pipeline.yaml, ci/prod/killswitch-pipeline.yaml, ci/sandbox/build-pipeline.yaml, ci/sandbox/deploy-pipeline.yaml, ci/sandbox/killswitch-pipeline.yaml, ci/sandbox/test-pki.yaml
Like #653 except backported and sorted out some missing changes.
=> Backport "Use dockerhubpull secrets to access DockerHub"

ci/build/build-pipeline.yaml, ci/deploy/deploy-pipeline.yaml, ci/deploy/killswitch-pipeline.yaml
=> Add more DockerHub credential plumbing

Dockerfile, cloudhsm/Dockerfile, cloudhsm/jdk-jce-image/Dockerfile, proxy-node-translator/build.gradle
See https://govukverify.atlassian.net/browse/EID-2074.
We’ve upgraded to the 'latest' already, we just want to upgrade to a specific version.
Tested by building the Dockerfiles locally
=> ☁️ EID-2074 Update cloudhsm client to v3.2.1
